package mx.com.inscitech.actinver.ws.contract;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class ClienteUnicoServicePortClient {
    public static void main(String[] args) {
        ClienteUnicoService_Service clienteUnicoService_Service = new ClienteUnicoService_Service();
        ClienteUnicoService clienteUnicoService = clienteUnicoService_Service.getClienteUnicoServicePort();
        // Add your code to call the desired methods.


    }
}
