package mx.com.inscitech.actinver.ws.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ClienteUnicoService", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ClienteUnicoService {


    /**
     *
     * @param contractInfo
     * @return
     *     returns mx.com.inscitech.actinver.ws.contract.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractInfo", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.contract.GetContractInfo")
    @ResponseWrapper(localName = "getContractInfoResponse", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.contract.GetContractInfoResponse")
    @Action(input = "http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/getContractInfoRequest",
            output = "http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/getContractInfoResponse")
    public ServiceResponse getContractInfo(@WebParam(name = "contractInfo", targetNamespace = "") ServiceRequest contractInfo);

    /**
     *
     * @param serviceConfig
     * @return
     *     returns mx.com.inscitech.actinver.ws.contract.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setServiceConfig", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.contract.SetServiceConfig")
    @ResponseWrapper(localName = "setServiceConfigResponse", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.contract.SetServiceConfigResponse")
    @Action(input = "http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/setServiceConfigRequest",
            output = "http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/setServiceConfigResponse")
    public ServiceResponse setServiceConfig(@WebParam(name = "ServiceConfig", targetNamespace = "") ServiceConfig serviceConfig);

}
