
package mx.com.inscitech.actinver.ws.contract;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ClienteUnicoService", targetNamespace = "http://contract.ws.actinver.inscitech.com.mx/",
                  wsdlLocation =
                  "http://127.0.0.1:7101/FiduciaWeb/ContractInfoService/ClienteUnicoServicePort?wsdl#%7Bhttp%3A%2F%2Fcontract.ws.actinver.inscitech.com.mx%2F%7DClienteUnicoService")
public class ClienteUnicoService_Service extends Service {

    private final static URL CLIENTEUNICOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTEUNICOSERVICE_EXCEPTION;
    private final static QName CLIENTEUNICOSERVICE_QNAME = new QName("http://contract.ws.actinver.inscitech.com.mx/", "ClienteUnicoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://127.0.0.1:7101/FiduciaWeb/ContractInfoService/ClienteUnicoServicePort?wsdl#%7Bhttp%3A%2F%2Fcontract.ws.actinver.inscitech.com.mx%2F%7DClienteUnicoService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTEUNICOSERVICE_WSDL_LOCATION = url;
        CLIENTEUNICOSERVICE_EXCEPTION = e;
    }

    public ClienteUnicoService_Service() {
        super(__getWsdlLocation(), CLIENTEUNICOSERVICE_QNAME);
    }

    public ClienteUnicoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTEUNICOSERVICE_QNAME, features);
    }

    public ClienteUnicoService_Service(URL wsdlLocation) {
        super(wsdlLocation, CLIENTEUNICOSERVICE_QNAME);
    }

    public ClienteUnicoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTEUNICOSERVICE_QNAME, features);
    }

    public ClienteUnicoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteUnicoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ClienteUnicoService
     */
    @WebEndpoint(name = "ClienteUnicoServicePort")
    public ClienteUnicoService getClienteUnicoServicePort() {
        return super.getPort(new QName("http://contract.ws.actinver.inscitech.com.mx/", "ClienteUnicoServicePort"), ClienteUnicoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteUnicoService
     */
    @WebEndpoint(name = "ClienteUnicoServicePort")
    public ClienteUnicoService getClienteUnicoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://contract.ws.actinver.inscitech.com.mx/", "ClienteUnicoServicePort"), ClienteUnicoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTEUNICOSERVICE_EXCEPTION != null) {
            throw CLIENTEUNICOSERVICE_EXCEPTION;
        }
        return CLIENTEUNICOSERVICE_WSDL_LOCATION;
    }

}
