<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://contract.ws.actinver.inscitech.com.mx/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://contract.ws.actinver.inscitech.com.mx/" name="ClienteUnicoService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://contract.ws.actinver.inscitech.com.mx/" schemaLocation="ClienteUnicoServicePort1.xsd"/>
    </xsd:schema>
  </types>
  <message name="getContractInfo">
    <part name="parameters" element="tns:getContractInfo"/>
  </message>
  <message name="getContractInfoResponse">
    <part name="parameters" element="tns:getContractInfoResponse"/>
  </message>
  <message name="setServiceConfig">
    <part name="parameters" element="tns:setServiceConfig"/>
  </message>
  <message name="setServiceConfigResponse">
    <part name="parameters" element="tns:setServiceConfigResponse"/>
  </message>
  <portType name="ClienteUnicoService">
    <operation name="getContractInfo">
      <input wsam:Action="http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/getContractInfoRequest" message="tns:getContractInfo"/>
      <output wsam:Action="http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/getContractInfoResponse" message="tns:getContractInfoResponse"/>
    </operation>
    <operation name="setServiceConfig">
      <input wsam:Action="http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/setServiceConfigRequest" message="tns:setServiceConfig"/>
      <output wsam:Action="http://contract.ws.actinver.inscitech.com.mx/ClienteUnicoService/setServiceConfigResponse" message="tns:setServiceConfigResponse"/>
    </operation>
  </portType>
  <binding name="ClienteUnicoServicePortBinding" type="tns:ClienteUnicoService">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="getContractInfo">
      <soap12:operation soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal"/>
      </output>
    </operation>
    <operation name="setServiceConfig">
      <soap12:operation soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="ClienteUnicoService">
    <port name="ClienteUnicoServicePort" binding="tns:ClienteUnicoServicePortBinding">
      <soap12:address location="http://127.0.0.1:7101/FiduciaWeb/ContractInfoService/ClienteUnicoServicePort"/>
    </port>
  </service>
</definitions>