export enum BIENES_MODULE {
    BIENES = 'BIENES.BIENES',
    CARGA_MASIVA = 'BIENES.CARGA_MASIVA',
    INDIVIDUALIZACION = 'BIENES.INDIVIDUALIZACION',
    ADQUIRIENTES = 'BIENES.ADQUIRIENTES',
    LIBERACIONES = 'BIENES.LIBERACIONES',
}

export enum INTERFASES_MODULE {
    INTERFASES = 'INTERFASES.INTERFASES',
}

export enum PLANES_MODULE {
    APERTURA_CIERRE = 'OPERACIONES.APERTURA_CIERRE',
}

export enum REPORTES_MODULE {
    REPORTE_BIENES = 'REPORTES.REPORTE_BIENES',
}

export enum SEGURIDAD_MODULE {
    USUARIOS = 'SEGURIDAD.USUARIOS',
}

export const modules = {
    BIENES: BIENES_MODULE,
    INTERFASES: INTERFASES_MODULE,
    PLANES: PLANES_MODULE,
    REPORTES: REPORTES_MODULE,
    SEGURIDAD: SEGURIDAD_MODULE,
};
