GRANT ALL ON SCHEMA "FIDUCIAWEB" TO "BRPFIDWEBINM";

SET search_path TO FIDUCIAWEB,public;
alter database "FIDUCIAWEB" set search_path TO "FIDUCIAWEB",public; 

--
-- Name: TABLE "CLAVES"; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT ON TABLE "FIDUCIAWEB"."CLAVES" TO "BRPFIDWEBINM";


--
-- Name: TABLE anteproy; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".anteproy TO "BRPFIDWEBINM";


--
-- Name: TABLE async_transactions; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".async_transactions TO "BRPFIDWEBINM";


--
-- Name: TABLE claves; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".claves TO "BRPFIDWEBINM";


--
-- Name: TABLE contrato; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".contrato TO "BRPFIDWEBINM";


--
-- Name: TABLE deposit; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".deposit TO "BRPFIDWEBINM";


--
-- Name: TABLE detliqui; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".detliqui TO "BRPFIDWEBINM";


--
-- Name: TABLE diasfera; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".diasfera TO "BRPFIDWEBINM";


--
-- Name: TABLE diasfval; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".diasfval TO "BRPFIDWEBINM";


--
-- Name: TABLE estados; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".estados TO "BRPFIDWEBINM";


--
-- Name: TABLE f_adquirentes; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_adquirentes TO "BRPFIDWEBINM";


--
-- Name: TABLE f_bgarliq; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_bgarliq TO "BRPFIDWEBINM";


--
-- Name: TABLE f_bienes; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_bienes TO "BRPFIDWEBINM";


--
-- Name: TABLE f_bienesgar; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_bienesgar TO "BRPFIDWEBINM";


--
-- Name: TABLE f_carta_liberacion; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_carta_liberacion TO "BRPFIDWEBINM";


--
-- Name: TABLE f_epassword; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_epassword TO "BRPFIDWEBINM";


--
-- Name: TABLE f_funcion; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_funcion TO "BRPFIDWEBINM";


--
-- Name: TABLE f_garantias; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_garantias TO "BRPFIDWEBINM";


--
-- Name: TABLE f_garantiash; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_garantiash TO "BRPFIDWEBINM";


--
-- Name: TABLE f_hpassword; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_hpassword TO "BRPFIDWEBINM";


--
-- Name: TABLE f_liquidaciones_bienes; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_liquidaciones_bienes TO "BRPFIDWEBINM";


--
-- Name: TABLE f_per_fun; Type: ACL; Schema: FIDUCIAWEB; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_per_fun TO "BRPFIDWEBINM";



--
-- Name: TABLE f_perfil; Type: ACL; Schema: FIDUCIAWEB; Owner: postgres
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_perfil TO "BRPFIDWEBINM";



--
-- Name: TABLE f_proceso_liberacion; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_proceso_liberacion TO "BRPFIDWEBINM";


--
-- Name: TABLE f_reporte; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_reporte TO "BRPFIDWEBINM";


--
-- Name: TABLE f_secuencial_fideicomiso; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_secuencial_fideicomiso TO "BRPFIDWEBINM";


--
-- Name: TABLE f_unidades; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_unidades TO "BRPFIDWEBINM";


--
-- Name: TABLE f_usuario; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_usuario TO "BRPFIDWEBINM";


--
-- Name: TABLE f_usuarioc; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".f_usuarioc TO "BRPFIDWEBINM";


--
-- Name: TABLE feccont; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".feccont TO "BRPFIDWEBINM";


--
-- Name: TABLE feriados; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".feriados TO "BRPFIDWEBINM";


--
-- Name: TABLE fideicom; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".fideicom TO "BRPFIDWEBINM";


--
-- Name: TABLE folios; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".folios TO "BRPFIDWEBINM";


--
-- Name: TABLE funcion; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".funcion TO "BRPFIDWEBINM";


--
-- Name: TABLE garantia; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".garantia TO "BRPFIDWEBINM";


--
-- Name: TABLE garantiah; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".garantiah TO "BRPFIDWEBINM";


--
-- Name: TABLE indices; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".indices TO "BRPFIDWEBINM";


--
-- Name: TABLE monedas; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".monedas TO "BRPFIDWEBINM";


--
-- Name: TABLE movimien; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".movimien TO "BRPFIDWEBINM";


--
-- Name: TABLE notarios; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".notarios TO "BRPFIDWEBINM";


--
-- Name: TABLE paises; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".paises TO "BRPFIDWEBINM";


--
-- Name: TABLE planes; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".planes TO "BRPFIDWEBINM";


--
-- Name: TABLE puestos; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".puestos TO "BRPFIDWEBINM";


--
-- Name: TABLE reporte_poliza; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".reporte_poliza TO "BRPFIDWEBINM";


--
-- Name: TABLE reportes; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".reportes TO "BRPFIDWEBINM";


--
-- Name: TABLE rutinas; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".rutinas TO "BRPFIDWEBINM";


--
-- Name: TABLE usuarios; Type: ACL; Schema: FIDUCIAWEB; 
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "FIDUCIAWEB".usuarios TO "BRPFIDWEBINM";

