--------------------------------------------------------
--  File created - Thursday-July-16-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANTEPROY
--------------------------------------------------------

  CREATE TABLE "ANTEPROY" 
   (	"ANT_NUM_PROSPECTO" NUMBER(10,0), 
	"ANT_FECHA_APERTURA" VARCHAR2(10), 
	"ANT_NUM_PROMOTOR" NUMBER(10,0), 
	"ANT_CVE_FORM_MAN" VARCHAR2(80), 
	"ANT_CVE_TIPO_NEG" VARCHAR2(25), 
	"ANT_CVE_CLASIF_PRO" VARCHAR2(50), 
	"ANT_NUM_PRODUCTO" NUMBER(10,0), 
	"ANT_CVE_COMITE" NUMBER(1,0), 
	"ANT_CVE_REVOCABLE" NUMBER(1,0), 
	"ANT_IMP_APERTURA" NUMBER(16,4), 
	"ANT_CVE_ST_PROSPEC" VARCHAR2(25), 
	"ANT_DES_GESTION" VARCHAR2(250), 
	"ANT_FEC_GESTION" VARCHAR2(10), 
	"ANT_PATRIMONIO" VARCHAR2(4000), 
	"ANT_NUM_ABOGADO" NUMBER(10,0), 
	"ANT_NOM_NEGOCIO" VARCHAR2(250), 
	"ANT_CVE_SITUACION" VARCHAR2(25), 
	"ANT_FEC_PRO_CONSTI" VARCHAR2(10), 
	"ANT_NOM_ACTIVIDAD" VARCHAR2(250), 
	"ANT_TIPO_CLIENT" VARCHAR2(25), 
	"ANT_TIPO_PUBLIC" VARCHAR2(25), 
	"ANT_TIPO_CONTACTO" VARCHAR2(25), 
	"ANT_NUM_ESCRITURA" VARCHAR2(25), 
	"ANT_NUM_NOTARIO" NUMBER(10,0), 
	"ANT_TIPO_ADMON" VARCHAR2(25), 
	"ANT_ANO_CONMOD1" NUMBER(4,0), 
	"ANT_MES_CONMOD1" NUMBER(2,0), 
	"ANT_DIA_CONMOD1" NUMBER(2,0), 
	"ANT_ANO_CONMOD2" NUMBER(4,0), 
	"ANT_MES_CONMOD2" NUMBER(2,0), 
	"ANT_DIA_CONMOD2" NUMBER(2,0), 
	"ANT_ANO_CONMOD3" NUMBER(4,0), 
	"ANT_MES_CONMOD3" NUMBER(2,0), 
	"ANT_DIA_CONMOD3" NUMBER(2,0), 
	"ANT_NUM_CONTRATO" NUMBER(10,0), 
	"ANT_SEGUIMIENTO" VARCHAR2(50), 
	"ANT_TIPO_NEG_SAT" NUMBER(10,0), 
	"ANT_MONEDA" VARCHAR2(50), 
	"ANT_CVE_AREA_INST" VARCHAR2(100), 
	"ANT_ARCHIVOS" NUMBER(1,0), 
	"ANT_CVE_CLASIF_SUB_PRO" VARCHAR2(255), 
	"ANT_NUM_ADMIN" NUMBER, 
	"ANT_UNE" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_ADQUIRENTES
--------------------------------------------------------

  CREATE TABLE "F_ADQUIRENTES" 
   (	"FADQ_ID_FIDEICOMISO" NUMBER(10,0), 
	"FADQ_ID_SUBCUENTA" NUMBER(10,0), 
	"FADQ_ID_BIEN" VARCHAR2(50), 
	"FADQ_ID_EDIFICIO" VARCHAR2(50), 
	"FADQ_ID_DEPTO" VARCHAR2(50), 
	"FADQ_ID_VENTA" NUMBER(10,0), 
	"FADQ_PERIODO" NUMBER(10,0), 
	"FADQ_NOMBRE_COMPRADOR" VARCHAR2(125), 
	"FADQ_VALOR" NUMBER(16,2), 
	"FADQ_MONEDA" NUMBER(10,0), 
	"FADQ_TIPO_VENTA" VARCHAR2(25), 
	"FADQ_TIPO_PLAZO" VARCHAR2(25), 
	"FADQ_NUM_PLAZO" NUMBER(10,0), 
	"FADQ_ENGANCHE" NUMBER(16,2), 
	"FADQ_ABONO" NUMBER(16,2), 
	"FADQ_SALDO" NUMBER(16,2), 
	"FADQ_PAGOS" NUMBER(10,0), 
	"FADQ_NOTARIO" NUMBER(10,0), 
	"FADQ_LOCALIDAD" VARCHAR2(50), 
	"FADQ_CV" VARCHAR2(25), 
	"FADQ_CONTRATO" VARCHAR2(35), 
	"FADQ_FOLIO" VARCHAR2(35), 
	"FADQ_REG_PUB" VARCHAR2(255), 
	"FADQ_FEC_ALTA" DATE, 
	"FADQ_FEC_MOD" DATE, 
	"FADQ_STATUS" VARCHAR2(25), 
	"FADQ_NOM_COMPRADOR" VARCHAR2(255), 
	"FADQ_NUM_ESCRCOM" VARCHAR2(30), 
	"FADQ_FEC_ESCRICOM" DATE, 
	"FADQ_EXP_CATAST" VARCHAR2(1000), 
	"FADQ_PROTOTIPO" VARCHAR2(255), 
	"FADQ_NUMERO_OFICIAL" VARCHAR2(255), 
	"FADQ_NOTARIA" VARCHAR2(255), 
	"FADQ_DELEGADO_FIDUCIARIO" VARCHAR2(255)
   ) ;
--------------------------------------------------------
--  DDL for Table DIASFERA
--------------------------------------------------------

  CREATE TABLE "DIASFERA" 
   (	"DFA_NUM_PAIS" NUMBER(10,0), 
	"DFA_ANO_FECHA" NUMBER(4,0), 
	"DFA_MES_FECHA" NUMBER(2,0), 
	"DFA_DIA_FECHA" NUMBER(2,0), 
	"DFA_DESC_FECHA" VARCHAR2(50), 
	"DFA_NUM_TIPO_DIA" NUMBER(4,0), 
	"DFA_CVE_PERIODO" VARCHAR2(30), 
	"DFA_CVE_DIA" VARCHAR2(30), 
	"DFA_CVE_MES" VARCHAR2(30), 
	"DFA_PERIODICIDAD" VARCHAR2(30), 
	"DFA_ANO_ALTA_REG" NUMBER(4,0), 
	"DFA_MES_ALTA_REG" NUMBER(2,0), 
	"DFA_DIA_ALTA_REG" NUMBER(2,0), 
	"DFA_ANO_ULT_MOD" NUMBER(4,0), 
	"DFA_MES_ULT_MOD" NUMBER(2,0), 
	"DFA_DIA_ULT_MOD" NUMBER(2,0), 
	"DFA_CVE_ST_DIASFERA" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table DIASFVAL
--------------------------------------------------------

  CREATE TABLE "DIASFVAL" 
   (	"DFV_NUM_PROGRAMA" NUMBER(10,0), 
	"DFV_NUM_EMISION" NUMBER(10,0), 
	"DFV_NUM_PAIS" NUMBER(4,0), 
	"DFV_ANO_ALTA_REG" NUMBER(4,0), 
	"DFV_MES_ALTA_REG" NUMBER(2,0), 
	"DFV_DIA_ALTA_REG" NUMBER(2,0), 
	"DFV_ANO_ULT_MOD" NUMBER(4,0), 
	"DFV_MES_ULT_MOD" NUMBER(2,0), 
	"DFV_DIA_ULT_MOD" NUMBER(2,0), 
	"DFV_CVE_ST_DIASFERA" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table FERIADOS
--------------------------------------------------------

  CREATE TABLE "FERIADOS" 
   (	"FER_NUM_PAIS" NUMBER(10,0), 
	"FER_FEC_MES" NUMBER(10,0), 
	"FER_FEC_DIA" NUMBER(10,0), 
	"FER_DESC_DIA_FER" VARCHAR2(40), 
	"FER_ANO_ALTA_REG" NUMBER(4,0), 
	"FER_MES_ALTA_REG" NUMBER(2,0), 
	"FER_DIA_ALTA_REG" NUMBER(2,0), 
	"FER_ANO_ULT_MOD" NUMBER(4,0), 
	"FER_MES_ULT_MOD" NUMBER(2,0), 
	"FER_DIA_ULT_MOD" NUMBER(2,0), 
	"FER_CVE_ST_FERIADO" VARCHAR2(25), 
	"FER_FEC_ANO" NUMBER(4,0)
   ) ;
--------------------------------------------------------
--  DDL for Table FIDEICOM
--------------------------------------------------------

  CREATE TABLE "FIDEICOM" 
   (	"FID_NUM_CONTRATO" NUMBER(10,0), 
	"FID_FIDEICOMITENTE" NUMBER(10,0), 
	"FID_NUM_PAIS" NUMBER(10,0), 
	"FID_NUM_RAMA" NUMBER(10,0), 
	"FID_NUM_SRAMA" NUMBER(10,0), 
	"FID_CVE_MIGRATORIA" VARCHAR2(25), 
	"FID_CVE_SEXO" VARCHAR2(1), 
	"FID_CVE_TIPO_PER" VARCHAR2(25), 
	"FID_NOM_FIDEICOM" VARCHAR2(250), 
	"FID_RFC" VARCHAR2(15), 
	"FID_FEC_NAC" NUMBER(10,0), 
	"FID_NOM_NACIONAL" VARCHAR2(50), 
	"FID_NUM_LADA_CASA" VARCHAR2(4), 
	"FID_NUM_TELEF_CASA" VARCHAR2(50), 
	"FID_NUM_LADA_OFIC" VARCHAR2(4), 
	"FID_NUM_TELEF_OFIC" VARCHAR2(50), 
	"FID_NUM_EXT_OFIC" VARCHAR2(10), 
	"FID_NUM_LADA_FAX" VARCHAR2(4), 
	"FID_NUM_TELEF_FAX" VARCHAR2(50), 
	"FID_NUM_EXT_FAX" VARCHAR2(10), 
	"FID_ANO_ALTA_REG" NUMBER(4,0), 
	"FID_MES_ALTA_REG" NUMBER(2,0), 
	"FID_DIA_ALTA_REG" NUMBER(2,0), 
	"FID_ANO_ULT_MOD" NUMBER(4,0), 
	"FID_MES_ULT_MOD" NUMBER(2,0), 
	"FID_DIA_ULT_MOD" NUMBER(2,0), 
	"FID_CVE_ST_FIDEICO" VARCHAR2(25), 
	"FID_CURP" VARCHAR2(20)
   ) ;
--------------------------------------------------------
--  DDL for Table FOLIOS
--------------------------------------------------------

  CREATE TABLE "FOLIOS" 
   (	"FOL_TIPO_FOLIO" NUMBER(10,0), 
	"FOL_NUM_FOLIO" NUMBER(10,0), 
	"FOL_CVE_ST_FOLIO" VARCHAR2(25), 
	"FOL_NUM_PRUEBA" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table CLAVES
--------------------------------------------------------

  CREATE TABLE "CLAVES" 
   (	"CVE_NUM_CLAVE" NUMBER(10,0), 
	"CVE_NUM_SEC_CLAVE" NUMBER(10,0), 
	"CVE_DESC_CLAVE" VARCHAR2(50), 
	"CVE_LIMINF_CLAVE" NUMBER(16,2), 
	"CVE_LIMSUP_CLAVE" NUMBER(38,0), 
	"CVE_FORMA_EMP_CVE" VARCHAR2(70), 
	"CVE_ANO_ALTA_REG" NUMBER(4,0), 
	"CVE_MES_ALTA_REG" NUMBER(2,0), 
	"CVE_DIA_ALTA_REG" NUMBER(2,0), 
	"CVE_ANO_ULT_MOD" NUMBER(4,0), 
	"CVE_MES_ULT_MOD" NUMBER(2,0), 
	"CVE_DIA_ULT_MOD" NUMBER(2,0), 
	"CVE_CVE_ST_CLAVE" VARCHAR2(25), 
	"CVE_PARAM1" VARCHAR2(50), 
	"CVE_DESC_PARAM1" VARCHAR2(50), 
	"CVE_PARAM2" VARCHAR2(50), 
	"CVE_DESC_PARAM2" VARCHAR2(50), 
	"CVE_PARAM3" VARCHAR2(50), 
	"CVE_DESC_PARAM3" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table F_BIENES
--------------------------------------------------------

  CREATE TABLE "F_BIENES" 
   (	"FBIF_ID_FIDEICOMISO" NUMBER(10,0), 
	"FBIF_ID_SUB_CUENTA" NUMBER(10,0), 
	"FBIF_ID_TIPO_BIEN" NUMBER(10,0), 
	"FBIF_ID_CVE_BIEN" VARCHAR2(80), 
	"FBIF_ID_BIEN" VARCHAR2(25), 
	"FBIF_IMP_BIEN" NUMBER(16,2), 
	"FBIF_IMP_ULT_VALUA" NUMBER(16,2), 
	"FBIF_PER_VALUACION" VARCHAR2(25), 
	"FBIF_DESC_BIEN" VARCHAR2(255), 
	"FBIF_FEC_ULT_VALUA" DATE, 
	"FBIF_FEC_INICIO" DATE, 
	"FBIF_FEC_FIN" DATE, 
	"FBIF_MONEDA" NUMBER(10,0), 
	"FBIF_IMP_MONEDA" NUMBER(16,2), 
	"FBIF_TIPO_CAMBIO" NUMBER(16,2), 
	"FBIF_TEX_COMENTARIO" VARCHAR2(300), 
	"FBIF_ST_BIEN" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table F_BIENESGAR
--------------------------------------------------------

  CREATE TABLE "F_BIENESGAR" 
   (	"FGRS_ID_FIDEICOMISO" NUMBER(10,0), 
	"FGRS_ID_SUBCUENTA" NUMBER(10,0), 
	"FORS_ID_GARANTIA" NUMBER(10,0), 
	"FORS_CVE_TIPO_GARANTIA" NUMBER(10,0), 
	"FORS_CVE_TIPO_BIEN" NUMBER(10,0), 
	"FORS_IDENTIFICACION" VARCHAR2(25), 
	"FORS_TEXTO_DESCRIP" VARCHAR2(500), 
	"FORS_TEX_COMENTARIO" VARCHAR2(255), 
	"FORS_IMP_BIEN" NUMBER(16,2), 
	"FORS_MONEDA" NUMBER(10,0), 
	"FORS_CVE_REVALUA" NUMBER(2,0), 
	"FORS_CVE_PER_VALUA" VARCHAR2(25), 
	"FORS_IMP_ULT_VALUA" NUMBER(16,2), 
	"FORS_FEC_ULT_VALUA" DATE, 
	"FORS_FEC_VENCIMIENTO" DATE, 
	"FORS_NUM_ESCRITURA" VARCHAR2(30), 
	"FORS_NUM_NOTARIO" VARCHAR2(20), 
	"FORS_CVE_STATUS" VARCHAR2(25), 
	"FORS_CVE_GRAHIPO" NUMBER(2,0), 
	"FORS_NUM_HIPOTECA" VARCHAR2(30), 
	"FORS_A_FAVOR" VARCHAR2(80), 
	"FORS_REGIMEN" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_BGARLIQ
--------------------------------------------------------

  CREATE TABLE "F_BGARLIQ" 
   (	"GLBE_ID_FIDEICOMISO" NUMBER(10,0), 
	"GLBE_ID_CREDITO" VARCHAR2(30), 
	"GLBE_ID_TIPO_CREDITO" VARCHAR2(35), 
	"GLBE_ID_DISPOSICION" NUMBER(10,0), 
	"GLBE_ID_SECUENCIAL" NUMBER(10,0), 
	"GLBE_ID_BENEFICIARIO" VARCHAR2(30), 
	"GLBE_NOMBRE_BEN" VARCHAR2(130), 
	"GLBE_IMP_CREDITO" NUMBER(16,2), 
	"GLBE_PJE_GARANTIA" NUMBER(12,4), 
	"GLBE_IMP_GARLIQ" NUMBER(16,2), 
	"GLBE_IMP_GARLIQ_LIB" NUMBER(20,3), 
	"GLBE_IMP_INTERESES" NUMBER(16,2), 
	"GLBE_FOLIO_CONSTANCIA" NUMBER(10,0), 
	"GLBE_FOLIO_LIBERACION" NUMBER(10,0), 
	"GLBE_TIPO_MOVTO" VARCHAR2(30), 
	"GLBE_IMP_MOVTO_CONST" NUMBER(16,2), 
	"GLBE_IMP_MOVTO_LIBERA" NUMBER(16,2), 
	"GLBE_CVE_STATUS" VARCHAR2(25), 
	"GLBE_RFC_CURP" VARCHAR2(25), 
	"GLBE_FECHA_SUS" VARCHAR2(10), 
	"GLBE_FECHA_VEN" VARCHAR2(10), 
	"GLBE_FECHA_PRO" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table F_CARTA_LIBERACION
--------------------------------------------------------

  CREATE TABLE "F_CARTA_LIBERACION" 
   (	"FLIB_ID_FIDEICOMISO" NUMBER(10,0), 
	"FLIB_ID_SUBCUENTA" NUMBER(10,0), 
	"FLIB_ID_BIEN" VARCHAR2(50), 
	"FLIB_ID_EDIFICIO" VARCHAR2(50), 
	"FLIB_ID_DEPTO" VARCHAR2(50), 
	"FLIB_NOM_EMPRESA" VARCHAR2(125), 
	"FLIB_NOM_AREA" VARCHAR2(125), 
	"FLIB_DIRECCION" VARCHAR2(500), 
	"FLIB_SITIO" VARCHAR2(125), 
	"FLIB_FECHA" DATE, 
	"FLIB_NOM_NOTARIO" VARCHAR2(125), 
	"FLIB_NOM_PUESTO" VARCHAR2(125), 
	"FLIB_DESC_FID_BEN" VARCHAR2(500), 
	"FLIB_DESC_SANEAMIENTO" VARCHAR2(500), 
	"FLIB_DESC_RESPONSABILIDAD" VARCHAR2(500), 
	"FLIB_DESC_OTORGAMIENTO" VARCHAR2(500), 
	"FLIB_TRANSMISION_REVERSION" VARCHAR2(125), 
	"FLIB_PARCIAL_TOTAL" VARCHAR2(125), 
	"FLIB_DESCRIPCION_INMUEBLE" VARCHAR2(500), 
	"FLIB_SUJETO_REGIMEN" NUMBER(10,0), 
	"FLIB_DESCRIPCION_REGIMEN1" VARCHAR2(500), 
	"FLIB_DESCRIPCION_REGIMEN2" VARCHAR2(500), 
	"FLIB_DESCRIPCION_REGIMEN3" VARCHAR2(500), 
	"FLIB_NOM_ADQUIRENTE" VARCHAR2(125), 
	"FLIB_NOM_CALLE" VARCHAR2(50), 
	"FLIB_NOM_COLONIA" VARCHAR2(50), 
	"FLIB_DELEGACION_MUNICIPIO" VARCHAR2(125), 
	"FLIB_NOM_POBLACION" VARCHAR2(50), 
	"FLIB_NOM_ESTADO" VARCHAR2(50), 
	"FLIB_TIPO_INMUEBLE" VARCHAR2(125), 
	"FLIB_INDIVISO" NUMBER(16,4), 
	"FLIB_NUM_ESCRITURA" VARCHAR2(50), 
	"FLIB_NOM_ENVIO" VARCHAR2(125), 
	"FLIB_EMAIL_ENVIO" VARCHAR2(125), 
	"FLIB_OBSERVACION" VARCHAR2(500), 
	"FLIB_NOM_DELEGADO" VARCHAR2(125), 
	"FLIB_NOM_FIRMA" VARCHAR2(125)
   ) ;
--------------------------------------------------------
--  DDL for Table F_FUNCION
--------------------------------------------------------

  CREATE TABLE "F_FUNCION" 
   (	"FFUN_ID_FUNCION" NUMBER(10,0), 
	"FFUN_NOM_MENU" VARCHAR2(100), 
	"FFUN_ID_PADRE" NUMBER(10,0), 
	"FFUN_NOMBRE_FUNCION" VARCHAR2(255), 
	"FFUN_ORDEN" NUMBER(2,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_GARANTIAS
--------------------------------------------------------

  CREATE TABLE "F_GARANTIAS" 
   (	"FGAR_ID_FIDEICOMISO" NUMBER(10,0), 
	"FGAR_ID_SUBCUENTA" NUMBER(10,0), 
	"FGAR_CVE_GARANTIA" NUMBER(10,0), 
	"FGAR_TEX_GARANTIA" VARCHAR2(500), 
	"FGAR_TEX_COMENTARIO" VARCHAR2(255), 
	"FGAR_CVE_REVALUA" NUMBER(10,0), 
	"FGAR_IMP_GARANTIA" NUMBER(16,2), 
	"FGAR_IMP_GARANTIZAD" NUMBER(16,2), 
	"FGAR_PJE_PICNORADO" NUMBER(16,4), 
	"FGAR_IMP_ULT_VALUA" NUMBER(16,2), 
	"FGAR_CVE_PER_VALUA" VARCHAR2(25), 
	"FGAR_FEC_ULT_VALUA" DATE, 
	"FGAR_FEC_INICIO" DATE, 
	"FGAR_FEC_FIN" DATE, 
	"FGAR_CVE_STATUS" VARCHAR2(25), 
	"FGAR_ES_GARANTIA" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_GARANTIASH
--------------------------------------------------------

  CREATE TABLE "F_GARANTIASH" 
   (	"FGAR_ID_FIDEICOMISO" NUMBER(10,0), 
	"FGAR_ID_SUBCUENTA" NUMBER(10,0), 
	"FGAR_CVE_GARANTIA" NUMBER(10,0), 
	"FGAR_TEX_GARANTIA" VARCHAR2(500), 
	"FGAR_TEX_COMENTARIO" VARCHAR2(255), 
	"FGAR_CVE_REVALUA" NUMBER(10,0), 
	"FGAR_IMP_GARANTIA" NUMBER(16,2), 
	"FGAR_IMP_GARANTIZAD" NUMBER(16,2), 
	"FGAR_PJE_PICNORADO" NUMBER(16,4), 
	"FGAR_IMP_ULT_VALUA" NUMBER(16,2), 
	"FGAR_CVE_PER_VALUA" VARCHAR2(25), 
	"FGAR_FEC_ULT_VALUA" DATE, 
	"FGAR_FEC_INICIO" DATE, 
	"FGAR_FEC_FIN" DATE, 
	"FGAR_CVE_STATUS" VARCHAR2(25), 
	"FGAR_ES_GARANTIA" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_HPASSWORD
--------------------------------------------------------

  CREATE TABLE "F_HPASSWORD" 
   (	"USU_NUM_USUARIO" NUMBER(10,0), 
	"USU_SEC_PASSWORD" NUMBER(10,0), 
	"USU_PASSWORD" VARCHAR2(2048), 
	"USU_FEC_CAMBIO" DATE
   ) ;
--------------------------------------------------------
--  DDL for Table F_PROCESO_LIBERACION
--------------------------------------------------------

  CREATE TABLE "F_PROCESO_LIBERACION" 
   (	"FPL_ID_FIDEICOMISO" NUMBER(10,0), 
	"FPL_ID_SUBCUENTA" NUMBER(10,0), 
	"FPL_ID_BIEN" VARCHAR2(50), 
	"FPL_ID_EDIFICIO" VARCHAR2(50), 
	"FPL_ID_DEPTO" VARCHAR2(50), 
	"FPL_NOTARIO" NUMBER(10,0), 
	"FPL_ADQUIRENTE" VARCHAR2(125), 
	"FPL_TERCERO" VARCHAR2(125), 
	"FPL_FIDEICOM_BENEFICI" VARCHAR2(125), 
	"FPL_NOM_PERSONA" VARCHAR2(125), 
	"FPL_NUM_LUGAR" VARCHAR2(125), 
	"FPL_NOM_PERSONA1" VARCHAR2(125), 
	"FPL_NUM_LUGAR1" VARCHAR2(125), 
	"FPL_FID_BEN_SANEAMIENTO" VARCHAR2(125), 
	"FPL_NOM_SANEAMIENTO" VARCHAR2(125), 
	"FPL_NUM_LUGAR_SANEAMIENTO" VARCHAR2(125), 
	"FPL_NOM_SANEAMIENTO1" VARCHAR2(125), 
	"FPL_NUM_LUGAR_SANEAMIENTO1" VARCHAR2(125), 
	"FPL_FID_BEN_RESPONSABILIDAD" VARCHAR2(125), 
	"FPL_NOM_RESPONSABILIDAD" VARCHAR2(125), 
	"FPL_NUM_LUGAR_RESPONSABILIDAD" VARCHAR2(125), 
	"FPL_NOM_RESPONSABILIDAD1" VARCHAR2(125), 
	"FPL_NUM_LUGAR_RESPONSABILIDAD1" VARCHAR2(125), 
	"FPL_FID_BEN_OTORGAMIENTO" VARCHAR2(125), 
	"FPL_NOM_OTORGAMIENTO" VARCHAR2(125), 
	"FPL_NUM_LUGAR_OTORGAMIENTO" VARCHAR2(125), 
	"FPL_NOM_OTORGAMIENTO1" VARCHAR2(125), 
	"FPL_NUM_LUGAR_OTORGAMIENTO1" VARCHAR2(125), 
	"FPL_TRANSMISION_REVERSION" VARCHAR2(125), 
	"FPL_PARCIAL_TOTAL" VARCHAR2(125), 
	"FPL_SUJETO_REGIMEN" NUMBER(10,0), 
	"FPL_TIPO_INMUEBLE" VARCHAR2(125), 
	"FPL_NOM_ENVIO" VARCHAR2(125), 
	"FPL_EMAIL_ENVIO" VARCHAR2(125), 
	"FPL_OBSERVACION" VARCHAR2(500), 
	"FPL_ESCRITURA" VARCHAR2(50), 
	"FPL_FEC_ESCRITURA" DATE, 
	"FPL_DELEGADO" VARCHAR2(125), 
	"FPL_FEC_FIRMA" DATE, 
	"FPL_CVE_STATUS" VARCHAR2(80)
   ) ;
--------------------------------------------------------
--  DDL for Table F_REPORTE
--------------------------------------------------------

  CREATE TABLE "F_REPORTE" 
   (	"FRCO_ID_REPORTE" NUMBER(10,0), 
	"FRCO_NOMBRE_REPORTE" VARCHAR2(20), 
	"FRCO_STATUS" VARCHAR2(20), 
	"FRCO_NUM_COLUMNAS" NUMBER(2,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_SECUENCIAL_FIDEICOMISO
--------------------------------------------------------

  CREATE TABLE "F_SECUENCIAL_FIDEICOMISO" 
   (	"FSF_ID_CVE_FIDEICOMISO" VARCHAR2(10), 
	"FSF_NUM_SECUENCIAL" NUMBER(10,0), 
	"FSF_CVE_ST_SCUENCIAL" VARCHAR2(80)
   ) ;
--------------------------------------------------------
--  DDL for Table F_UNIDADES
--------------------------------------------------------

  CREATE TABLE "F_UNIDADES" 
   (	"FUNI_ID_FIDEICOMISO" NUMBER(10,0), 
	"FUNI_ID_SUBCUENTA" NUMBER(10,0), 
	"FUNI_ID_BIEN" VARCHAR2(50), 
	"FUNI_ID_EDIFICIO" VARCHAR2(50), 
	"FUNI_ID_DEPTO" VARCHAR2(50), 
	"FUNI_TIPO" VARCHAR2(50), 
	"FUNI_NIVELES" VARCHAR2(25), 
	"FUNI_CALLE_NUM" VARCHAR2(50), 
	"FUNI_NOM_COLONIA" VARCHAR2(50), 
	"FUNI_NOM_POBLACION" VARCHAR2(50), 
	"FUNI_CODIGO_POSTAL" VARCHAR2(10), 
	"FUNI_NUM_ESTADO" VARCHAR2(30), 
	"FUNI_NUM_PAIS" VARCHAR2(30), 
	"FUNI_COLINDANCIAS" VARCHAR2(300), 
	"FUNI_MEDIDAS" VARCHAR2(300), 
	"FUNI_ESTACIONAMIENTO1" VARCHAR2(10), 
	"FUNI_SUPERFICIE1" VARCHAR2(10), 
	"FUNI_ESTACIONAMIENTO2" VARCHAR2(10), 
	"FUNI_SUPERFICIE2" VARCHAR2(10), 
	"FUNI_ESTACIONAMIENTO3" VARCHAR2(10), 
	"FUNI_SUPERFICIE3" VARCHAR2(10), 
	"FUNI_ROOF_GARDEN" VARCHAR2(10), 
	"FUNI_ROOF_SUPERFICIE" VARCHAR2(10), 
	"FUNI_SOTANO" VARCHAR2(10), 
	"FUNI_SOTANO_SUPERFICIE" VARCHAR2(10), 
	"FUNI_INDIVISO" NUMBER(16,4), 
	"FUNI_PRECIO" NUMBER(16,2), 
	"FUNI_PRECIO_CATASTRO" NUMBER(16,2), 
	"FUNI_ULTIMO_AVALUO" NUMBER(16,2), 
	"FUNI_FECHA_ULTIMO_AVALUO" DATE, 
	"FUNI_MONEDA" NUMBER(10,0), 
	"FUNI_ACTO1" VARCHAR2(255), 
	"FUNI_ACTO2" VARCHAR2(255), 
	"FUNI_ACTO3" VARCHAR2(255), 
	"FUNI_ACTO4" VARCHAR2(255), 
	"FUNI_NOTARIO" NUMBER(10,0), 
	"FUNI_FECHA_REVERSION" DATE, 
	"FUNI_LOCALIDAD_NOTA" VARCHAR2(50), 
	"FUNI_NUM_ESCRITURA" VARCHAR2(50), 
	"FUNI_FOLIO_REAL" VARCHAR2(50), 
	"FUNI_FECHA_TRASLADO_DOMINIO" DATE, 
	"FUNI_STATUS" VARCHAR2(25), 
	"FUNI_CVE_GRAHIPO" NUMBER(2,0), 
	"FUNI_NUM_HIPOTECA" VARCHAR2(30), 
	"FUNI_A_FAVOR" VARCHAR2(80), 
	"FUNI_NUM_CATASTRO" VARCHAR2(255), 
	"FUNI_NOM_FIDEICOMISO" VARCHAR2(255), 
	"FUNI_NUMERO_CATASTRO" NUMBER(16,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_USUARIO
--------------------------------------------------------

  CREATE TABLE "F_USUARIO" 
   (	"FUSU_ID_USUARIO" VARCHAR2(20), 
	"FUSU_CONTRASENA" VARCHAR2(30), 
	"FUSU_NOMBRE_USUARIO" VARCHAR2(150), 
	"FUSU_PREGUNTA_SECRETA" NUMBER(*,0), 
	"FUSU_RESPUESTA_SECRETA" VARCHAR2(20), 
	"FUSU_STATUS" VARCHAR2(20), 
	"FUSU_EMAIL" VARCHAR2(100), 
	"FPER_ID_PERFIL" NUMBER(10,0), 
	"FUSU_IMP_MAXIMO" NUMBER(*,0), 
	"FUSU_ULT_ACCESO" DATE, 
	"FUSU_MTEO" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table F_USUARIOC
--------------------------------------------------------

  CREATE TABLE "F_USUARIOC" 
   (	"FUSU_ID_USUARIO" VARCHAR2(20), 
	"FUSU_CONTRASENA" VARCHAR2(30), 
	"FUSU_NOMBRE_USUARIO" VARCHAR2(150), 
	"FUSU_PREGUNTA_SECRETA" NUMBER(*,0), 
	"FUSU_RESPUESTA_SECRETA" VARCHAR2(20), 
	"FUSU_STATUS" VARCHAR2(20), 
	"FUSU_EMAIL" VARCHAR2(100), 
	"FPER_ID_PERFIL" NUMBER(10,0), 
	"FUSU_IMP_MAXIMO" NUMBER(*,0), 
	"FUSU_ULT_ACCESO" DATE, 
	"FUSU_MTEO" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table GARANTIA
--------------------------------------------------------

  CREATE TABLE "GARANTIA" 
   (	"GRN_NUM_CONTRATO" NUMBER(10,0), 
	"GRN_SUB_CONTRATO" NUMBER(10,0), 
	"GRN_CVE_VALORES" NUMBER(10,0), 
	"GRN_CVE_OTROS" NUMBER(10,0), 
	"GRN_CVE_INMUEBLES" NUMBER(10,0), 
	"GRN_CVE_MUEBLES" NUMBER(10,0), 
	"GRN_CVE_REVALUA" NUMBER(10,0), 
	"GRN_CVE_NUMERARIO" NUMBER(10,0), 
	"GRN_IMP_GARANTI" NUMBER(16,2), 
	"GRN_IMP_GARANTIZAD" NUMBER(16,2), 
	"GRN_IMP_ULT_VALUA" NUMBER(16,2), 
	"GRN_CVE_PER_VALUA" VARCHAR2(25), 
	"GRN_FEC_ANO_INICIO" NUMBER(4,0), 
	"GRN_FEC_DIA_INICIO" NUMBER(2,0), 
	"GRN_FEC_MES_INICIO" NUMBER(2,0), 
	"GRN_FEC_ANO_FIN" NUMBER(4,0), 
	"GRN_FEC_MES_FIN" NUMBER(2,0), 
	"GRN_FEC_DIA_FIN" NUMBER(2,0), 
	"GRN_FEC_ULT_VALUA" VARCHAR2(10), 
	"GRN_TEX_GARANTIA" LONG, 
	"GRN_TEX_COMENTARIO" VARCHAR2(255), 
	"GRN_CVE_STATUS" VARCHAR2(25), 
	"GRN_IMP_NUMERARIO" NUMBER(16,2), 
	"GRN_FECH_NUMERARIO" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table GARANTIAH
--------------------------------------------------------

  CREATE TABLE "GARANTIAH" 
   (	"GRN_NUM_CONTRATO" NUMBER(10,0), 
	"GRN_SUB_CONTRATO" NUMBER(10,0), 
	"GRN_CVE_VALORES" NUMBER(10,0), 
	"GRN_CVE_OTROS" NUMBER(10,0), 
	"GRN_CVE_INMUEBLES" NUMBER(10,0), 
	"GRN_CVE_MUEBLES" NUMBER(10,0), 
	"GRN_CVE_REVALUA" NUMBER(10,0), 
	"GRN_CVE_NUMERARIO" NUMBER(10,0), 
	"GRN_IMP_GARANTI" NUMBER(16,2), 
	"GRN_IMP_GARANTIZAD" NUMBER(16,2), 
	"GRN_IMP_ULT_VALUA" NUMBER(16,2), 
	"GRN_CVE_PER_VALUA" VARCHAR2(25), 
	"GRN_FEC_ANO_INICIO" NUMBER(4,0), 
	"GRN_FEC_DIA_INICIO" NUMBER(2,0), 
	"GRN_FEC_MES_INICIO" NUMBER(2,0), 
	"GRN_FEC_ANO_FIN" NUMBER(4,0), 
	"GRN_FEC_MES_FIN" NUMBER(2,0), 
	"GRN_FEC_DIA_FIN" NUMBER(2,0), 
	"GRN_FEC_ULT_VALUA" VARCHAR2(10), 
	"GRN_TEX_GARANTIA" LONG, 
	"GRN_TEX_COMENTARIO" VARCHAR2(255), 
	"GRN_CVE_STATUS" VARCHAR2(25), 
	"GRN_IMP_NUMERARIO" NUMBER(16,2), 
	"GRN_FECH_NUMERARIO" VARCHAR2(10)
   ) ;
--------------------------------------------------------
--  DDL for Table MOVIMIEN
--------------------------------------------------------

  CREATE TABLE "MOVIMIEN" 
   (	"MOV_ANO_MOVTO" NUMBER(4,0), 
	"MOV_MES_MOVTO" NUMBER(2,0), 
	"MOV_DIA_MOVTO" NUMBER(2,0), 
	"MOV_NUM_CONTRATO" NUMBER(10,0), 
	"MOV_SUB_CONTRATO" NUMBER(10,0), 
	"MOV_FOLIO_OPERA" NUMBER(10,0), 
	"MOV_NUM_MODULO" NUMBER(10,0), 
	"MOV_NUM_TRANSAC" NUMBER(10,0), 
	"MOV_NUM_USUARIO" NUMBER(10,0), 
	"MOV_DESC_MOVTO" VARCHAR2(125), 
	"MOV_HR_TRANSAC" NUMBER(10,0), 
	"MOV_MIN_TRANSAC" NUMBER(10,0), 
	"MOV_IMP_MOVTO" NUMBER(16,2), 
	"MOV_CVE_TIPO_MERCA" NUMBER(10,0), 
	"MOV_NUM_INSTRUME" NUMBER(10,0), 
	"MOV_NUM_SEC_EMIS" NUMBER(10,0), 
	"MOV_NUM_TITULOS" NUMBER(10,0), 
	"MOV_CVE_IMPRE_EDO" NUMBER(10,0), 
	"MOV_CVE_ENT_SAL" VARCHAR2(1), 
	"MOV_ANO_ALTA_REG" NUMBER(4,0), 
	"MOV_MES_ALTA_REG" NUMBER(2,0), 
	"MOV_DIA_ALTA_REG" NUMBER(2,0), 
	"MOV_ANO_ULT_MOD" NUMBER(4,0), 
	"MOV_MES_ULT_MOD" NUMBER(2,0), 
	"MOV_DIA_ULT_MOD" NUMBER(2,0), 
	"MOV_CVE_ST_MOVTO" VARCHAR2(25), 
	"MOV_CVE_ACUM_EDCTA" VARCHAR2(2)
   ) ;
--------------------------------------------------------
--  DDL for Table MONEDAS
--------------------------------------------------------

  CREATE TABLE "MONEDAS" 
   (	"MON_NUM_PAIS" NUMBER(10,0), 
	"MON_NOM_MONEDA" VARCHAR2(50), 
	"MON_ANO_ALTA_REG" NUMBER(4,0), 
	"MON_MES_ALTA_REG" NUMBER(2,0), 
	"MON_DIA_ALTA_REG" NUMBER(2,0), 
	"MON_ANO_ULT_MOD" NUMBER(4,0), 
	"MON_MES_ULT_MOD" NUMBER(2,0), 
	"MON_DIA_ULT_MOD" NUMBER(2,0), 
	"MON_CVE_ST_MONEDA" VARCHAR2(25), 
	"MON_SIGLA" VARCHAR2(5) DEFAULT 'XXX'
   ) ;
--------------------------------------------------------
--  DDL for Table PAISES
--------------------------------------------------------

  CREATE TABLE "PAISES" 
   (	"PAI_NUM_PAIS" NUMBER(10,0), 
	"PAI_NOM_PAIS" VARCHAR2(50), 
	"PAI_ABR_PAIS" VARCHAR2(30), 
	"PAI_ANO_ALTA_REG" NUMBER(4,0), 
	"PAI_MES_ALTA_REG" NUMBER(2,0), 
	"PAI_DIA_ALTA_REG" NUMBER(2,0), 
	"PAI_ANO_ULT_MOD" NUMBER(4,0), 
	"PAI_MES_ULT_MOD" NUMBER(2,0), 
	"PAI_DIA_ULT_MOD" NUMBER(2,0), 
	"PAI_CVE_ST_PAIS" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table PLANES
--------------------------------------------------------

  CREATE TABLE "PLANES" 
   (	"PLA_CVE_FASE_PROD" VARCHAR2(36), 
	"PLA_DESC_FASE_PROD" VARCHAR2(255), 
	"PLA_CVE_PER_APLICA" VARCHAR2(25), 
	"PLA_CVE_CH_CONTROL" NUMBER(10,0), 
	"PLA_ANO_APLICACION" NUMBER(4,0), 
	"PLA_MES_APLICACION" NUMBER(2,0), 
	"PLA_DIA_APLICACION" NUMBER(2,0), 
	"PLA_HORA_APLICA" NUMBER(4,0), 
	"PLA_ANO_ALTA_REG" NUMBER(4,0), 
	"PLA_MES_ALTA_REG" NUMBER(2,0), 
	"PLA_DIA_ALTA_REG" NUMBER(2,0), 
	"PLA_ANO_ULT_MOD" NUMBER(4,0), 
	"PLA_MES_ULT_MOD" NUMBER(2,0), 
	"PLA_DIA_ULT_MOD" NUMBER(2,0), 
	"PLA_CVE_ST_PLAN" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table PUESTOS
--------------------------------------------------------

  CREATE TABLE "PUESTOS" 
   (	"PUE_NUM_PUESTO" NUMBER(10,0), 
	"PUE_NOM_PUESTO" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table REPORTES
--------------------------------------------------------

  CREATE TABLE "REPORTES" 
   (	"REP_NUM_REPORTE" NUMBER(10,0), 
	"REP_NOM_FISICO_REP" VARCHAR2(50), 
	"REP_NOM_REPORTE" VARCHAR2(50), 
	"REP_DESC_REPORTE" VARCHAR2(255), 
	"REP_CVE_CLIENTE" NUMBER(10,0), 
	"REP_CVE_USUARIO" NUMBER(10,0), 
	"REP_CVE_OFICIAL" NUMBER(10,0), 
	"REP_TIPO_PAPELERIA" VARCHAR2(25), 
	"REP_IMP_COSTO_HOJA" NUMBER(16,2), 
	"REP_ANO_ALTA_REG" NUMBER(4,0), 
	"REP_MES_ALTA_REG" NUMBER(2,0), 
	"REP_DIA_ALTA_REG" NUMBER(2,0), 
	"REP_ANO_ULT_MOD" NUMBER(4,0), 
	"REP_MES_ULT_MOD" NUMBER(2,0), 
	"REP_DIA_ULT_MOD" NUMBER(2,0), 
	"REP_CVE_ST_REPORTE" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table REPORTE_POLIZA
--------------------------------------------------------

  CREATE TABLE "REPORTE_POLIZA" 
   (	"RAS_NUM_CONTRATO" NUMBER(10,0), 
	"RAS_FOLIO_OPERA" NUMBER(10,0), 
	"RAS_SEC_ASIENTO" NUMBER(10,0), 
	"RAS_NOM_CONTRATO" VARCHAR2(255), 
	"RAS_DESC_MOVTO" VARCHAR2(500), 
	"RAS_DESC_ASIENTO" VARCHAR2(500), 
	"RAS_NUM_CTAM" NUMBER(4,0), 
	"RAS_NUM_SCTA" NUMBER(2,0), 
	"RAS_NUM_SSCTA" NUMBER(2,0), 
	"RAS_NUM_SSSCTA" NUMBER(2,0), 
	"RAS_NUM_SSSSCTA" NUMBER(2,0), 
	"RAS_NUM_SSSSSCTA" NUMBER(2,0), 
	"RAS_NUM_AUX2" NUMBER(10,0), 
	"RAS_NUM_AUX3" NUMBER(10,0), 
	"RAS_IMP_CARGO" NUMBER(16,2), 
	"RAS_IMP_ABONO" NUMBER(16,2), 
	"RAS_FOLIO_CTO" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table RUTINAS
--------------------------------------------------------

  CREATE TABLE "RUTINAS" 
   (	"RUT_ID_RUTINA" VARCHAR2(36), 
	"RUT_NOM_RUTINA" VARCHAR2(36), 
	"RUT_DESC_RUTINA" VARCHAR2(255), 
	"RUT_CVE_AREA_RESP" VARCHAR2(25), 
	"RUT_CVE_PROCESO" VARCHAR2(25), 
	"RUT_CVE_PERIOD" VARCHAR2(25), 
	"RUT_CVE_IMPRESION" NUMBER(10,0), 
	"RUT_CVE_PAPELERIA" VARCHAR2(25), 
	"RUT_CVE_RESP_DATOS" NUMBER(10,0), 
	"RUT_NUM_USUARIO" NUMBER(10,0), 
	"RUT_CVE_BLOQUEO" NUMBER(10,0), 
	"RUT_TEXTO_BLOQUEO" VARCHAR2(255), 
	"RUT_FEC_INIC_BLOQ" VARCHAR2(10), 
	"RUT_FEC_FIN_BLOQ" VARCHAR2(10), 
	"RUT_ANO_ALTA_REG" NUMBER(4,0), 
	"RUT_MES_ALTA_REG" NUMBER(2,0), 
	"RUT_DIA_ALTA_REG" NUMBER(2,0), 
	"RUT_ANO_ULT_MOD" NUMBER(4,0), 
	"RUT_MES_ULT_MOD" NUMBER(2,0), 
	"RUT_DIA_ULT_MOD" NUMBER(2,0), 
	"RUT_CVE_ST_RUTINAS" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USUARIOS" 
   (	"USU_NUM_USUARIO" NUMBER(10,0), 
	"USU_NOM_USUARIO" VARCHAR2(50), 
	"USU_TIPO_USUARIO" VARCHAR2(50), 
	"USU_NUM_PUESTO" NUMBER(10,0), 
	"USU_NOM_PUESTO" VARCHAR2(50), 
	"USU_PASSWORD" VARCHAR2(50), 
	"USU_ANO_ALTA_REG" NUMBER(4,0), 
	"USU_MES_ALTA_REG" NUMBER(2,0), 
	"USU_DIA_ALTA_REG" NUMBER(2,0), 
	"USU_ANO_ULT_MOD" NUMBER(4,0), 
	"USU_MES_ULT_MOD" NUMBER(2,0), 
	"USU_DIA_ULT_MOD" NUMBER(2,0), 
	"USU_CVE_ST_USUARIO" VARCHAR2(25), 
	"USU_NUM_NIVEL1" NUMBER(10,0), 
	"USU_NUM_NIVEL2" NUMBER(10,0), 
	"USU_NUM_NIVEL3" NUMBER(10,0), 
	"USU_NUM_NIVEL4" NUMBER(10,0), 
	"USU_NUM_NIVEL5" NUMBER(10,0), 
	"USU_CENTRO_LOGRO" NUMBER(10,0), 
	"USU_CENTRO_COSTO" NUMBER(10,0), 
	"USU_PTCE_GPOT" NUMBER(2,0), 
	"USU_FECHA_ULT_ACCESO" DATE, 
	"USU_FECHA_PASSWORD" DATE, 
	"USU_ESTATUS_SEGURIDAD" NUMBER(1,0), 
	"USU_TOKEN" NUMBER(1,0) DEFAULT 0, 
	"USU_MONTO_AUTORIZADO" NUMBER(16,2), 
	"USU_PERFIL_INTERNO" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table F_EPASSWORD
--------------------------------------------------------

  CREATE TABLE "F_EPASSWORD" 
   (	"USU_NUM_USUARIO" NUMBER(10,0), 
	"USU_FEC_ERROR" DATE, 
	"USU_NUM_ERROR" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table FUNCION
--------------------------------------------------------

  CREATE TABLE "FUNCION" 
   (	"FUN_ID_OPCION" NUMBER(10,0), 
	"FUN_NOM_MENU" VARCHAR2(100), 
	"FUN_ID_PADRE" NUMBER(10,0), 
	"FUN_NOM_OPCION" VARCHAR2(100)
   ) ;
--------------------------------------------------------
--  DDL for Table DEPOSIT
--------------------------------------------------------

  CREATE TABLE "DEPOSIT" 
   (	"DPO_FOLIO_RCP" NUMBER(10,0), 
	"DPO_FOLIO_OPERA" NUMBER(10,0), 
	"DPO_NUM_OPERACION" NUMBER(10,0), 
	"DPO_NUM_SEC_OPERA" NUMBER(10,0), 
	"DPO_NUM_MODULO" NUMBER(10,0), 
	"DPO_NUM_TRANSAC" NUMBER(10,0), 
	"DPO_NUM_CONTRATO" NUMBER(10,0), 
	"DPO_SUB_CONTRATO" NUMBER(10,0), 
	"DPO_SUB_PROGRAMA" NUMBER(10,0), 
	"DPO_NUM_PERS_FID" NUMBER(10,0), 
	"DPO_FOLIO_OPER_SIS" NUMBER(10,0), 
	"DPO_BENEF_XTERCER" NUMBER(10,0), 
	"DPO_COTIZACION" NUMBER(16,2), 
	"DPO_NOM_PERS_FID" VARCHAR2(50), 
	"DPO_TIPO_PERS_FID" VARCHAR2(20), 
	"DPO_CVE_TIPO_DEP" NUMBER(2,0), 
	"DPO_IMP_DEPOSITO" NUMBER(16,2), 
	"DPO_NUM_MONEDA" NUMBER(10,0), 
	"DPO_NUM_CHEQUE" NUMBER(10,0), 
	"DPO_CVE_TIPO_CTA" VARCHAR2(50), 
	"DPO_NUM_BANCO" NUMBER(10,0), 
	"DPO_NOM_BANCO" VARCHAR2(50), 
	"DPO_NUM_PLAZA" NUMBER(10,0), 
	"DPO_NOM_PLAZA" VARCHAR2(50), 
	"DPO_NUM_PAIS" NUMBER(10,0), 
	"DPO_CTA_BANXICO" NUMBER(20,0), 
	"DPO_DIR_APER_CTA" VARCHAR2(50), 
	"DPO_CODIGO_TRANS" VARCHAR2(25), 
	"DPO_CONCEPTO" VARCHAR2(250), 
	"DPO_NUM_CUENTA" NUMBER(30,0), 
	"DPO_FECHA" VARCHAR2(10), 
	"DPO_NOM_INSTITU" VARCHAR2(50), 
	"DPO_NUM_REFE" NUMBER(10,0), 
	"DPO_NUM_SUCURSAL" NUMBER(10,0), 
	"DPO_NOM_SUCURSAL" VARCHAR2(50), 
	"DPO_NUM_INICIATIVA" NUMBER(10,0), 
	"DPO_NUM_CTAM" NUMBER(10,0), 
	"DPO_NUM_SCTA" NUMBER(10,0), 
	"DPO_NUM_SSCTA" NUMBER(10,0), 
	"DPO_NUM_SSSCTA" NUMBER(10,0), 
	"DPO_NUM_ENTE" NUMBER(10,0), 
	"DPO_NOM_AREA" VARCHAR2(25), 
	"DPO_ENTIDAD_FIN" NUMBER(10,0), 
	"DPO_CONTRATO_INTER" NUMBER(11,0), 
	"DPO_POLITICA" NUMBER(2,0), 
	"DPO_ANO_RCP" NUMBER(4,0), 
	"DPO_MES_RCP" NUMBER(2,0), 
	"DPO_DIA_RCP" NUMBER(2,0), 
	"DPO_ANO_ALTA_REG" NUMBER(4,0), 
	"DPO_MES_ALTA_REG" NUMBER(2,0), 
	"DPO_DIA_ALTA_REG" NUMBER(2,0), 
	"DPO_ANO_ULT_MOD" NUMBER(4,0), 
	"DPO_MES_ULT_MOD" NUMBER(2,0), 
	"DPO_DIA_ULT_MOD" NUMBER(2,0), 
	"DPO_CVE_ST_DEPOSI" VARCHAR2(25), 
	"DPO_CONIVA" NUMBER(2,0), 
	"DPO_IMP_IVA" NUMBER(16,2), 
	"DPO_FOLIO_AGEND" NUMBER(10,0), 
	"DPO_RUBRO" NUMBER(10,0)
   ) ;
--------------------------------------------------------
--  DDL for Table DETLIQUI
--------------------------------------------------------

  CREATE TABLE "DETLIQUI" 
   (	"DEL_FOLIO_OPERA" NUMBER(10,0), 
	"DEL_NUM_OPERACION" NUMBER(10,0), 
	"DEL_NUM_SEC_OPERA" NUMBER(10,0), 
	"DEL_NUM_MODULO" NUMBER(10,0), 
	"DEL_NUM_TRANSAC" NUMBER(10,0), 
	"DEL_NUM_CONTRATO" NUMBER(10,0), 
	"DEL_SUB_CONTRATO" NUMBER(10,0), 
	"DEL_SUB_PROGRAMA" NUMBER(10,0), 
	"DEL_NUM_PERS_FID" NUMBER(10,0), 
	"DEL_NOM_PERS_FID" VARCHAR2(100), 
	"DEL_TIPO_PERS_FID" VARCHAR2(50), 
	"DEL_FOLIO_OPER_SIS" NUMBER(10,0), 
	"DEL_BENEF_XTERCER" NUMBER(10,0), 
	"DEL_IMP_LIQUIDAR" NUMBER(16,2), 
	"DEL_PARIDAD" NUMBER(16,2), 
	"DEL_CVE_TIPO_LIQ" NUMBER(2,0), 
	"DEL_NUM_MONEDA" NUMBER(2,0), 
	"DEL_CVE_TIPO_CTA" VARCHAR2(25), 
	"DEL_NUM_BANCO" NUMBER(10,0), 
	"DEL_NOM_BANCO" VARCHAR2(50), 
	"DEL_NUM_PLAZA" NUMBER(5,0), 
	"DEL_NOM_PLAZA" VARCHAR2(50), 
	"DEL_NUM_SUCURSAL" NUMBER(10,0), 
	"DEL_NUM_CUENTA" VARCHAR2(35), 
	"DEL_NUM_PAIS" NUMBER(10,0), 
	"DEL_NUM_CHEQUE" NUMBER(10,0), 
	"DEL_CTA_BANXICO" VARCHAR2(20), 
	"DEL_DIR_APER_CTA" VARCHAR2(50), 
	"DEL_CODIGO_TRANS" VARCHAR2(30), 
	"DEL_NUM_INICIATIVA" NUMBER(10,0), 
	"DEL_NUM_CTAM" NUMBER(10,0), 
	"DEL_NUM_SCTA" NUMBER(10,0), 
	"DEL_NUM_SSCTA" NUMBER(10,0), 
	"DEL_NUM_SSSCTA" NUMBER(10,0), 
	"DEL_NOM_AREA" VARCHAR2(50), 
	"DEL_CONCEPTO" VARCHAR2(250), 
	"DEL_ANO_ALTA_REG" NUMBER(4,0), 
	"DEL_MES_ALTA_REG" NUMBER(2,0), 
	"DEL_DIA_ALTA_REG" NUMBER(2,0), 
	"DEL_ANO_ULT_MOD" NUMBER(4,0), 
	"DEL_MES_ULT_MOD" NUMBER(2,0), 
	"DEL_DIA_ULT_MOD" NUMBER(2,0), 
	"DEL_CVE_ST_DETLIQU" VARCHAR2(25), 
	"DEL_RUBRO" NUMBER(10,0), 
	"DEL_ENTIDAD_FIN" NUMBER(10,0), 
	"DEL_CONTRATO_INTER" NUMBER(11,0)
   ) ;
--------------------------------------------------------
--  DDL for Table FECCONT
--------------------------------------------------------

  CREATE TABLE "FECCONT" 
   (	"FCO_CVE_TIPO_FECHA" VARCHAR2(25), 
	"FCO_ANO_DIA" NUMBER(4,0), 
	"FCO_MES_DIA" NUMBER(2,0), 
	"FCO_DIA_DIA" NUMBER(2,0), 
	"FCO_ANO_APLI_CONTA" NUMBER(4,0), 
	"FCO_MES_APLI_CONTA" NUMBER(2,0), 
	"FCO_DIA_APLI_CONTA" NUMBER(2,0), 
	"FCO_ANO_ULT_CIERRE" NUMBER(4,0), 
	"FCO_MES_ULT_CIERRE" NUMBER(2,0), 
	"FCO_DIA_ULT_CIERRE" NUMBER(2,0), 
	"FCO_DIAS_OPER_ANO" NUMBER(10,0), 
	"FCO_DIAS_OPER_SIST" NUMBER(10,0), 
	"FCO_ANO_INI_OPERS" NUMBER(4,0), 
	"FCO_MES_INI_OPERS" NUMBER(2,0), 
	"FCO_DIA_INI_OPERS" NUMBER(2,0), 
	"FCO_ANO_ALTA_REG" NUMBER(4,0), 
	"FCO_MES_ALTA_REG" NUMBER(2,0), 
	"FCO_DIA_ALTA_REG" NUMBER(2,0), 
	"FCO_ANO_ULT_MOD" NUMBER(4,0), 
	"FCO_MES_ULT_MOD" NUMBER(2,0), 
	"FCO_DIA_ULT_MOD" NUMBER(2,0), 
	"FCO_CVE_ST_FECCONT" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table INDICES
--------------------------------------------------------

  CREATE TABLE "INDICES" 
   (	"IND_CVE_INDICE" VARCHAR2(25), 
	"IND_ANO_INDICE" NUMBER(4,0), 
	"IND_MES_INDICE" NUMBER(2,0), 
	"IND_DIA_INDICE" NUMBER(2,0), 
	"IND_VALOR_INDICE" NUMBER(16,8), 
	"IND_ANO_ALTA_REG" NUMBER(4,0), 
	"IND_MES_ALTA_REG" NUMBER(2,0), 
	"IND_DIA_ALTA_REG" NUMBER(2,0), 
	"IND_ANO_ULT_MOD" NUMBER(4,0), 
	"IND_MES_ULT_MOD" NUMBER(2,0), 
	"IND_DIA_ULT_MOD" NUMBER(2,0), 
	"IND_CVE_ST_INDICE" VARCHAR2(25)
   ) ;
--------------------------------------------------------
--  DDL for Table NOTARIOS
--------------------------------------------------------

  CREATE TABLE "NOTARIOS" 
   (	"NOT_NUM_NOTARIO" NUMBER(10,0), 
	"NOT_NUM_OFIC_NOTA" NUMBER(10,0), 
	"NOT_NOM_NOTARIO" VARCHAR2(50), 
	"NOT_LOCALIDAD_NOTA" VARCHAR2(50), 
	"NOT_RFC" VARCHAR2(15), 
	"NOT_CALLE_NUM" VARCHAR2(50), 
	"NOT_NOM_COLONIA" VARCHAR2(50), 
	"NOT_NOM_POBLACION" VARCHAR2(50), 
	"NOT_CODIGO_POSTAL" NUMBER(10,0), 
	"NOT_NUM_ESTADO" NUMBER(10,0), 
	"NOT_NOM_ESTADO" VARCHAR2(50), 
	"NOT_NUM_PAIS" NUMBER(3,0), 
	"NOT_NOM_PAIS" VARCHAR2(50), 
	"NOT_CVE_LADA1_OFIC" VARCHAR2(4), 
	"NOT_TELEF1_OFIC" VARCHAR2(20), 
	"NOT_NUM_EXT1_OFIC" VARCHAR2(10), 
	"NOT_CVE_LADA2_OFIC" VARCHAR2(4), 
	"NOT_TELEF2_OFIC" VARCHAR2(20), 
	"NOT_NUM_EXT2_OFIC" VARCHAR2(10), 
	"NOT_NUM_LADA_FAX" VARCHAR2(4), 
	"NOT_NUM_TELEF_FAX" VARCHAR2(20), 
	"NOT_NUM_EXT_FAX" VARCHAR2(10), 
	"NOT_ANO_ALTA_REG" NUMBER(4,0), 
	"NOT_MES_ALTA_REG" NUMBER(2,0), 
	"NOT_DIA_ALTA_REG" NUMBER(2,0), 
	"NOT_ANO_ULT_MOD" NUMBER(4,0), 
	"NOT_MES_ULT_MOD" NUMBER(2,0), 
	"NOT_DIA_ULT_MOD" NUMBER(2,0), 
	"NOT_CVE_ST_NOTARIO" VARCHAR2(25), 
	"NOT_E_MAIL" VARCHAR2(50), 
	"NOT_NOM_OPERADOR" VARCHAR2(50), 
	"NOT_NOM_DELEGACION" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Table CONTRATO
--------------------------------------------------------

  CREATE TABLE "CONTRATO" 
   (	"CTO_NUM_CONTRATO" NUMBER(10,0), 
	"CTO_NUM_CLIENTE" NUMBER(10,0), 
	"CTO_NUM_CTO_EJE" NUMBER(10,0), 
	"CTO_CVE_TIPO_NEG" VARCHAR2(100), 
	"CTO_CVE_CLAS_PROD" VARCHAR2(100), 
	"CTO_NUM_PRODUCTO" NUMBER(10,0), 
	"CTO_NOM_CONTRATO" VARCHAR2(1000), 
	"CTO_CVE_FORMA_MAN" VARCHAR2(100), 
	"CTO_CVE_TIPO_PER" VARCHAR2(25), 
	"CTO_CVE_RETENCION" VARCHAR2(25), 
	"CTO_CVE_COMITE_TEC" NUMBER(4,0), 
	"CTO_CVE_ART_28" NUMBER(4,0), 
	"CTO_CVE_EXCLU_30" NUMBER(4,0), 
	"CTO_CVE_MON_EXT" NUMBER(4,0), 
	"CTO_CVE_REVOCABLE" NUMBER(4,0), 
	"CTO_CVE_REP_PROD" NUMBER(4,0), 
	"CTO_NUM_OFICIO_EXE" VARCHAR2(20), 
	"CTO_REG_NAL_INV_EX" VARCHAR2(20), 
	"CTO_ANO_APERTURA" NUMBER(4,0), 
	"CTO_MES_APERTURA" NUMBER(2,0), 
	"CTO_DIA_APERTURA" NUMBER(2,0), 
	"CTO_ANO_VENCIM" NUMBER(4,0), 
	"CTO_MES_VENCIM" NUMBER(2,0), 
	"CTO_DIA_VENCIM" NUMBER(2,0), 
	"CTO_ANO_ANIVERS" NUMBER(4,0), 
	"CTO_MES_ANIVERS" NUMBER(2,0), 
	"CTO_DIA_ANIVERS" NUMBER(2,0), 
	"CTO_ANO_CANCELA" NUMBER(4,0), 
	"CTO_MES_CANCELA" NUMBER(2,0), 
	"CTO_DIA_CANCELA" NUMBER(2,0), 
	"CTO_FEC_INSC_RNIE" VARCHAR2(20), 
	"CTO_ANO_ALTA_REG" NUMBER(4,0), 
	"CTO_MES_ALTA_REG" NUMBER(2,0), 
	"CTO_DIA_ALTA_REG" NUMBER(2,0), 
	"CTO_ANO_ULT_MOD" NUMBER(4,0), 
	"CTO_MES_ULT_MOD" NUMBER(2,0), 
	"CTO_DIA_ULT_MOD" NUMBER(2,0), 
	"CTO_CVE_ST_CONTRAT" VARCHAR2(25), 
	"CTO_CVE_SUBCTO" NUMBER(4,0), 
	"CTO_NUM_NIVEL1" NUMBER(10,0), 
	"CTO_NUM_NIVEL2" NUMBER(10,0), 
	"CTO_NUM_NIVEL3" NUMBER(10,0), 
	"CTO_NUM_NIVEL4" NUMBER(10,0), 
	"CTO_NUM_NIVEL5" NUMBER(10,0), 
	"CTO_REG_SHCP" VARCHAR2(25), 
	"CTO_CVE_SHCP" NUMBER(2,0), 
	"CTO_REG_GOBDF" VARCHAR2(25), 
	"CTO_CVE_GOBDF" NUMBER(2,0), 
	"CTO_RAMA" NUMBER(10,0), 
	"CTO_SUB_RAMA" NUMBER(10,0), 
	"CTO_NOM_ACTIVIDAD" VARCHAR2(80), 
	"CTO_TIPO_CLIENT" VARCHAR2(25), 
	"CTO_TIPO_PUBLIC" VARCHAR2(25), 
	"CTO_TIPO_CONTACTO" VARCHAR2(25), 
	"CTO_NUM_ESCRITURA" VARCHAR2(25), 
	"CTO_NUM_NOTARIO" NUMBER(10,0), 
	"CTO_TIPO_ADMON" VARCHAR2(25), 
	"CTO_CVE_REQ_SORS" NUMBER(10,0), 
	"CTO_NUM_EXP_SORS" VARCHAR2(14), 
	"CTO_FEC_ACT_SHCP" VARCHAR2(10), 
	"CTO_FOSEG" VARCHAR2(1) DEFAULT NULL, 
	"CTO_ENVIO_MENS" NUMBER(1,0), 
	"CTO_FIRMAS_MANCOMUNADAS" NUMBER(1,0), 
	"CTO_EST_INTERFID" CHAR(2), 
	"CTO_TIPO_CONT" VARCHAR2(25), 
	"CTO_TIPO_FISO" NUMBER(9,0), 
	"CTO_MONEDA" NUMBER(10,0), 
	"CTO_CVE_AREA_INST" VARCHAR2(100)
   ) ;

--------------------------------------------------------
--  DDL for Index ANTEPROY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTEPROY_PK" ON "ANTEPROY" ("ANT_NUM_PROSPECTO") 
  ;
--------------------------------------------------------
--  DDL for Index CLAVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLAVES_PK" ON "CLAVES" ("CVE_NUM_CLAVE", "CVE_NUM_SEC_CLAVE") 
  ;
--------------------------------------------------------
--  DDL for Index CLAVES_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "CLAVES_NU_IDX1" ON "CLAVES" ("CVE_NUM_CLAVE") 
  ;
--------------------------------------------------------
--  DDL for Index CLAVES_NU_IDX2
--------------------------------------------------------

  CREATE INDEX "CLAVES_NU_IDX2" ON "CLAVES" ("CVE_NUM_SEC_CLAVE") 
  ;
--------------------------------------------------------
--  DDL for Index CLAVES_NU_IDX3
--------------------------------------------------------

  CREATE INDEX "CLAVES_NU_IDX3" ON "CLAVES" ("CVE_NUM_CLAVE", "CVE_DESC_CLAVE") 
  ;
--------------------------------------------------------
--  DDL for Index DIASFERA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIASFERA_PK" ON "DIASFERA" ("DFA_NUM_PAIS", "DFA_ANO_FECHA", "DFA_MES_FECHA", "DFA_DIA_FECHA") 
  ;
--------------------------------------------------------
--  DDL for Index DIASFVAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DIASFVAL_PK" ON "DIASFVAL" ("DFV_NUM_PROGRAMA", "DFV_NUM_EMISION", "DFV_NUM_PAIS") 
  ;
--------------------------------------------------------
--  DDL for Index FERIADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERIADOS_PK" ON "FERIADOS" ("FER_FEC_MES", "FER_FEC_DIA", "FER_FEC_ANO", "FER_NUM_PAIS") 
  ;
--------------------------------------------------------
--  DDL for Index FECCONT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FECCONT_PK" ON "FECCONT" ("FCO_CVE_TIPO_FECHA") 
  ;
--------------------------------------------------------
--  DDL for Index FOLIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FOLIOS_PK" ON "FOLIOS" ("FOL_TIPO_FOLIO") 
  ;
--------------------------------------------------------
--  DDL for Index F_BIENESGAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_BIENESGAR_PK" ON "F_BIENESGAR" ("FGRS_ID_FIDEICOMISO", "FGRS_ID_SUBCUENTA", "FORS_ID_GARANTIA", "FORS_CVE_TIPO_GARANTIA", "FORS_CVE_TIPO_BIEN") 
  ;
--------------------------------------------------------
--  DDL for Index F_HPASSWORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_HPASSWORD_PK" ON "F_HPASSWORD" ("USU_NUM_USUARIO", "USU_SEC_PASSWORD") 
  ;
--------------------------------------------------------
--  DDL for Index F_EPASSWORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_EPASSWORD_PK" ON "F_EPASSWORD" ("USU_NUM_USUARIO", "USU_FEC_ERROR") 
  ;
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Index F_FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_FUNCION_PK" ON "F_FUNCION" ("FFUN_ID_FUNCION") 
  ;
--------------------------------------------------------
--  DDL for Index F_GARANTIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_GARANTIAS_PK" ON "F_GARANTIAS" ("FGAR_ID_FIDEICOMISO", "FGAR_ID_SUBCUENTA", "FGAR_CVE_GARANTIA") 
  ;

--------------------------------------------------------
--  DDL for Index F_PERFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_PERFIL_PK" ON "F_PERFIL" ("FPER_ID_PERFIL") 
  ;
--------------------------------------------------------
--  DDL for Index F_PROCESO_LIBERACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_PROCESO_LIBERACION_PK" ON "F_PROCESO_LIBERACION" ("FPL_ID_FIDEICOMISO", "FPL_ID_SUBCUENTA", "FPL_ID_BIEN", "FPL_ID_EDIFICIO", "FPL_ID_DEPTO") 
  ;
--------------------------------------------------------
--  DDL for Index F_UNIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_UNIDADES_PK" ON "F_UNIDADES" ("FUNI_ID_FIDEICOMISO", "FUNI_ID_SUBCUENTA", "FUNI_ID_BIEN", "FUNI_ID_EDIFICIO", "FUNI_ID_DEPTO") 
  ;
--------------------------------------------------------
--  DDL for Index F_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_USUARIO_PK" ON "F_USUARIO" ("FUSU_ID_USUARIO") 
  ;
--------------------------------------------------------
--  DDL for Index GARANTIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARANTIA_PK" ON "GARANTIA" ("GRN_SUB_CONTRATO", "GRN_NUM_CONTRATO") 
  ;
--------------------------------------------------------
--  DDL for Index INDICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INDICES_PK" ON "INDICES" ("IND_CVE_INDICE", "IND_ANO_INDICE", "IND_MES_INDICE", "IND_DIA_INDICE") 
  ;
--------------------------------------------------------
--  DDL for Index MONEDAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MONEDAS_PK" ON "MONEDAS" ("MON_NOM_MONEDA", "MON_NUM_PAIS") 
  ;
--------------------------------------------------------
--  DDL for Index MOVIMIEN_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "MOVIMIEN_NU_IDX1" ON "MOVIMIEN" ("MOV_NUM_MODULO") 
  ;
--------------------------------------------------------
--  DDL for Index MOVIMIEN_NU_IDX2
--------------------------------------------------------

  CREATE INDEX "MOVIMIEN_NU_IDX2" ON "MOVIMIEN" ("MOV_FOLIO_OPERA") 
  ;
--------------------------------------------------------
--  DDL for Index MOVIMIEN_NU_IDX3
--------------------------------------------------------

  CREATE INDEX "MOVIMIEN_NU_IDX3" ON "MOVIMIEN" ("MOV_NUM_CONTRATO") 
  ;
--------------------------------------------------------
--  DDL for Index MOVIMIEN_NU_IDX4
--------------------------------------------------------

  CREATE INDEX "MOVIMIEN_NU_IDX4" ON "MOVIMIEN" ("MOV_ANO_MOVTO", "MOV_MES_MOVTO") 
  ;
--------------------------------------------------------
--  DDL for Index MOVIMIEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOVIMIEN_PK" ON "MOVIMIEN" ("MOV_ANO_MOVTO", "MOV_MES_MOVTO", "MOV_DIA_MOVTO", "MOV_NUM_CONTRATO", "MOV_SUB_CONTRATO", "MOV_FOLIO_OPERA", "MOV_NUM_MODULO", "MOV_NUM_TRANSAC") 
  ;
--------------------------------------------------------
--  DDL for Index MONEDAS_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "MONEDAS_NU_IDX1" ON "MONEDAS" ("MON_NUM_PAIS") 
  ;
--------------------------------------------------------
--  DDL for Index NOTARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTARIOS_PK" ON "NOTARIOS" ("NOT_NUM_NOTARIO") 
  ;
--------------------------------------------------------
--  DDL for Index PAISES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PAISES_PK" ON "PAISES" ("PAI_NUM_PAIS") 
  ;
--------------------------------------------------------
--  DDL for Index REPORTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPORTES_PK" ON "REPORTES" ("REP_NUM_REPORTE") 
  ;
--------------------------------------------------------
--  DDL for Index PUESTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PUESTOS_PK" ON "PUESTOS" ("PUE_NUM_PUESTO") 
  ;
--------------------------------------------------------
--  DDL for Index CONTRATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTRATO_PK" ON "CONTRATO" ("CTO_NUM_CONTRATO") 
  ;
--------------------------------------------------------
--  DDL for Index DEPOSIT_FOLIO
--------------------------------------------------------

  CREATE INDEX "DEPOSIT_FOLIO" ON "DEPOSIT" ("DPO_FOLIO_OPERA") 
  ;
--------------------------------------------------------
--  DDL for Index DEPOSIT_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "DEPOSIT_NU_IDX1" ON "DEPOSIT" ("DPO_NUM_MONEDA") 
  ;
--------------------------------------------------------
--  DDL for Index DEPOSIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEPOSIT_PK" ON "DEPOSIT" ("DPO_FOLIO_RCP", "DPO_FOLIO_OPERA", "DPO_CVE_TIPO_DEP") 
  ;
--------------------------------------------------------
--  DDL for Index DETLIQUI_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "DETLIQUI_NU_IDX1" ON "DETLIQUI" ("DEL_NUM_MODULO", "DEL_NUM_TRANSAC") 
  ;
--------------------------------------------------------
--  DDL for Index DETLIQUI_NU_IDX2
--------------------------------------------------------

  CREATE INDEX "DETLIQUI_NU_IDX2" ON "DETLIQUI" ("DEL_ANO_ALTA_REG", "DEL_MES_ALTA_REG", "DEL_DIA_ALTA_REG") 
  ;
--------------------------------------------------------
--  DDL for Index DETLIQUI_NU_IDX3
--------------------------------------------------------

  CREATE INDEX "DETLIQUI_NU_IDX3" ON "DETLIQUI" ("DEL_SUB_PROGRAMA") 
  ;
--------------------------------------------------------
--  DDL for Index DETLIQUI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DETLIQUI_PK" ON "DETLIQUI" ("DEL_FOLIO_OPERA") 
  ;
--------------------------------------------------------
--  DDL for Index F_ADQUIRENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "F_ADQUIRENTES_PK" ON "F_ADQUIRENTES" ("FADQ_ID_FIDEICOMISO", "FADQ_ID_SUBCUENTA", "FADQ_ID_BIEN", "FADQ_ID_EDIFICIO", "FADQ_ID_DEPTO", "FADQ_ID_VENTA") 
  ;
--------------------------------------------------------
--  DDL for Index FIDEICOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIDEICOM_PK" ON "FIDEICOM" ("FID_NUM_CONTRATO", "FID_FIDEICOMITENTE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C0014878
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0014878" ON "F_REPORTE" ("FRCO_ID_REPORTE") 
  ;
--------------------------------------------------------
--  DDL for Index FSF_ID_CVE_FIDEICOMISO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FSF_ID_CVE_FIDEICOMISO_PK" ON "F_SECUENCIAL_FIDEICOMISO" ("FSF_ID_CVE_FIDEICOMISO", "FSF_NUM_SECUENCIAL") 
  ;
--------------------------------------------------------
--  DDL for Index GARANTIAH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GARANTIAH_PK" ON "GARANTIAH" ("GRN_SUB_CONTRATO", "GRN_NUM_CONTRATO") 
  ;
--------------------------------------------------------
--  DDL for Index PLANES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PLANES_PK" ON "PLANES" ("PLA_CVE_FASE_PROD") 
  ;
--------------------------------------------------------
--  DDL for Index REPORTE_POLIZA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REPORTE_POLIZA_PK" ON "REPORTE_POLIZA" ("RAS_NUM_CONTRATO", "RAS_FOLIO_OPERA", "RAS_SEC_ASIENTO", "RAS_NUM_CTAM", "RAS_NUM_SCTA", "RAS_NUM_SSCTA", "RAS_NUM_SSSCTA", "RAS_NUM_SSSSCTA", "RAS_NUM_SSSSSCTA") 
  ;
--------------------------------------------------------
--  DDL for Index RUTINAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RUTINAS_PK" ON "RUTINAS" ("RUT_ID_RUTINA") 
  ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIOS_PK" ON "USUARIOS" ("USU_NUM_USUARIO") 
  ;
--------------------------------------------------------
--  DDL for Index USUARIOS_NU_IDX1
--------------------------------------------------------

  CREATE INDEX "USUARIOS_NU_IDX1" ON "USUARIOS" ("USU_NUM_NIVEL1", "USU_NUM_NIVEL2", "USU_NUM_NIVEL3", "USU_NUM_NIVEL4", "USU_NUM_NIVEL5") 
  ;
--------------------------------------------------------
--  DDL for Index FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FUNCION_PK" ON "FUNCION" ("FUN_ID_OPCION") 
  ;

--------------------------------------------------------
--  Constraints for Table ANTEPROY
--------------------------------------------------------

  ALTER TABLE "ANTEPROY" MODIFY ("ANT_NUM_PROSPECTO" NOT NULL ENABLE);
  ALTER TABLE "ANTEPROY" MODIFY ("ANT_NUM_PROMOTOR" NOT NULL ENABLE);
  ALTER TABLE "ANTEPROY" MODIFY ("ANT_NUM_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "ANTEPROY" ADD CONSTRAINT "ANTEPROY_PK" PRIMARY KEY ("ANT_NUM_PROSPECTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_ADQUIRENTES
--------------------------------------------------------

  ALTER TABLE "F_ADQUIRENTES" MODIFY ("FADQ_ID_FIDEICOMISO" NOT NULL ENABLE);
  ALTER TABLE "F_ADQUIRENTES" MODIFY ("FADQ_ID_SUBCUENTA" NOT NULL ENABLE);
  ALTER TABLE "F_ADQUIRENTES" MODIFY ("FADQ_ID_BIEN" NOT NULL ENABLE);
  ALTER TABLE "F_ADQUIRENTES" MODIFY ("FADQ_ID_EDIFICIO" NOT NULL ENABLE);
  ALTER TABLE "F_ADQUIRENTES" MODIFY ("FADQ_ID_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "F_ADQUIRENTES" ADD CONSTRAINT "F_ADQUIRENTES_PK" PRIMARY KEY ("FADQ_ID_FIDEICOMISO", "FADQ_ID_SUBCUENTA", "FADQ_ID_BIEN", "FADQ_ID_EDIFICIO", "FADQ_ID_DEPTO", "FADQ_ID_VENTA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIASFERA
--------------------------------------------------------

  ALTER TABLE "DIASFERA" MODIFY ("DFA_NUM_PAIS" CONSTRAINT "SYS_C0045294" NOT NULL ENABLE);
  ALTER TABLE "DIASFERA" MODIFY ("DFA_ANO_FECHA" CONSTRAINT "SYS_C0045295" NOT NULL ENABLE);
  ALTER TABLE "DIASFERA" MODIFY ("DFA_MES_FECHA" CONSTRAINT "SYS_C0045296" NOT NULL ENABLE);
  ALTER TABLE "DIASFERA" MODIFY ("DFA_DIA_FECHA" CONSTRAINT "SYS_C0045297" NOT NULL ENABLE);
  ALTER TABLE "DIASFERA" ADD CONSTRAINT "DIASFERA_PK" PRIMARY KEY ("DFA_NUM_PAIS", "DFA_ANO_FECHA", "DFA_MES_FECHA", "DFA_DIA_FECHA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIASFVAL
--------------------------------------------------------

  ALTER TABLE "DIASFVAL" MODIFY ("DFV_NUM_PROGRAMA" NOT NULL ENABLE);
  ALTER TABLE "DIASFVAL" MODIFY ("DFV_NUM_EMISION" NOT NULL ENABLE);
  ALTER TABLE "DIASFVAL" MODIFY ("DFV_NUM_PAIS" NOT NULL ENABLE);
  ALTER TABLE "DIASFVAL" ADD CONSTRAINT "DIASFVAL_PK" PRIMARY KEY ("DFV_NUM_PROGRAMA", "DFV_NUM_EMISION", "DFV_NUM_PAIS")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FERIADOS
--------------------------------------------------------

  ALTER TABLE "FERIADOS" MODIFY ("FER_NUM_PAIS" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_FEC_MES" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_FEC_DIA" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" MODIFY ("FER_FEC_ANO" NOT NULL ENABLE);
  ALTER TABLE "FERIADOS" ADD CONSTRAINT "FERIADOS_PK" PRIMARY KEY ("FER_FEC_MES", "FER_FEC_DIA", "FER_FEC_ANO", "FER_NUM_PAIS")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FIDEICOM
--------------------------------------------------------

  ALTER TABLE "FIDEICOM" MODIFY ("FID_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "FIDEICOM" MODIFY ("FID_FIDEICOMITENTE" NOT NULL ENABLE);
  ALTER TABLE "FIDEICOM" ADD CONSTRAINT "FIDEICOM_PK" PRIMARY KEY ("FID_NUM_CONTRATO", "FID_FIDEICOMITENTE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOLIOS
--------------------------------------------------------

  ALTER TABLE "FOLIOS" MODIFY ("FOL_TIPO_FOLIO" NOT NULL ENABLE);
  ALTER TABLE "FOLIOS" MODIFY ("FOL_NUM_PRUEBA" NOT NULL ENABLE);
  ALTER TABLE "FOLIOS" ADD CONSTRAINT "FOLIOS_PK" PRIMARY KEY ("FOL_TIPO_FOLIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLAVES
--------------------------------------------------------

  ALTER TABLE "CLAVES" MODIFY ("CVE_NUM_CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_NUM_SEC_CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" MODIFY ("CVE_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "CLAVES" ADD CONSTRAINT "CLAVES_PK" PRIMARY KEY ("CVE_NUM_CLAVE", "CVE_NUM_SEC_CLAVE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_BIENESGAR
--------------------------------------------------------

  ALTER TABLE "F_BIENESGAR" MODIFY ("FGRS_ID_FIDEICOMISO" NOT NULL ENABLE);
  ALTER TABLE "F_BIENESGAR" MODIFY ("FGRS_ID_SUBCUENTA" NOT NULL ENABLE);
  ALTER TABLE "F_BIENESGAR" MODIFY ("FORS_ID_GARANTIA" NOT NULL ENABLE);
  ALTER TABLE "F_BIENESGAR" MODIFY ("FORS_IMP_BIEN" NOT NULL ENABLE);
  ALTER TABLE "F_BIENESGAR" ADD CONSTRAINT "F_BIENESGAR_PK" PRIMARY KEY ("FGRS_ID_FIDEICOMISO", "FGRS_ID_SUBCUENTA", "FORS_ID_GARANTIA", "FORS_CVE_TIPO_GARANTIA", "FORS_CVE_TIPO_BIEN")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_FUNCION
--------------------------------------------------------

  ALTER TABLE "F_FUNCION" MODIFY ("FFUN_ID_FUNCION" NOT NULL ENABLE);
  ALTER TABLE "F_FUNCION" ADD CONSTRAINT "F_FUNCION_PK" PRIMARY KEY ("FFUN_ID_FUNCION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_GARANTIAS
--------------------------------------------------------

  ALTER TABLE "F_GARANTIAS" MODIFY ("FGAR_ID_FIDEICOMISO" NOT NULL ENABLE);
  ALTER TABLE "F_GARANTIAS" MODIFY ("FGAR_ID_SUBCUENTA" NOT NULL ENABLE);
  ALTER TABLE "F_GARANTIAS" ADD CONSTRAINT "F_GARANTIAS_PK" PRIMARY KEY ("FGAR_ID_FIDEICOMISO", "FGAR_ID_SUBCUENTA", "FGAR_CVE_GARANTIA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_HPASSWORD
--------------------------------------------------------

  ALTER TABLE "F_HPASSWORD" MODIFY ("USU_NUM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "F_HPASSWORD" MODIFY ("USU_SEC_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "F_HPASSWORD" MODIFY ("USU_FEC_CAMBIO" NOT NULL ENABLE);
  ALTER TABLE "F_HPASSWORD" ADD CONSTRAINT "F_HPASSWORD_PK" PRIMARY KEY ("USU_NUM_USUARIO", "USU_SEC_PASSWORD")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_PROCESO_LIBERACION
--------------------------------------------------------

  ALTER TABLE "F_PROCESO_LIBERACION" ADD CONSTRAINT "F_PROCESO_LIBERACION_PK" PRIMARY KEY ("FPL_ID_FIDEICOMISO", "FPL_ID_SUBCUENTA", "FPL_ID_BIEN", "FPL_ID_EDIFICIO", "FPL_ID_DEPTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_REPORTE
--------------------------------------------------------

  ALTER TABLE "F_REPORTE" MODIFY ("FRCO_ID_REPORTE" NOT NULL ENABLE);
  ALTER TABLE "F_REPORTE" ADD PRIMARY KEY ("FRCO_ID_REPORTE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_SECUENCIAL_FIDEICOMISO
--------------------------------------------------------

  ALTER TABLE "F_SECUENCIAL_FIDEICOMISO" ADD CONSTRAINT "FSF_ID_CVE_FIDEICOMISO_PK" PRIMARY KEY ("FSF_ID_CVE_FIDEICOMISO", "FSF_NUM_SECUENCIAL")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_UNIDADES
--------------------------------------------------------

  ALTER TABLE "F_UNIDADES" MODIFY ("FUNI_ID_FIDEICOMISO" NOT NULL ENABLE);
  ALTER TABLE "F_UNIDADES" MODIFY ("FUNI_ID_SUBCUENTA" NOT NULL ENABLE);
  ALTER TABLE "F_UNIDADES" MODIFY ("FUNI_ID_BIEN" NOT NULL ENABLE);
  ALTER TABLE "F_UNIDADES" MODIFY ("FUNI_ID_EDIFICIO" NOT NULL ENABLE);
  ALTER TABLE "F_UNIDADES" MODIFY ("FUNI_ID_DEPTO" NOT NULL ENABLE);
  ALTER TABLE "F_UNIDADES" ADD CONSTRAINT "F_UNIDADES_PK" PRIMARY KEY ("FUNI_ID_FIDEICOMISO", "FUNI_ID_SUBCUENTA", "FUNI_ID_BIEN", "FUNI_ID_EDIFICIO", "FUNI_ID_DEPTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_USUARIO
--------------------------------------------------------

  ALTER TABLE "F_USUARIO" MODIFY ("FUSU_ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "F_USUARIO" ADD CONSTRAINT "F_USUARIO_PK" PRIMARY KEY ("FUSU_ID_USUARIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_USUARIOC
--------------------------------------------------------

  ALTER TABLE "F_USUARIOC" MODIFY ("FUSU_ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GARANTIA
--------------------------------------------------------

  ALTER TABLE "GARANTIA" MODIFY ("GRN_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "GARANTIA" MODIFY ("GRN_SUB_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "GARANTIA" ADD CONSTRAINT "GARANTIA_PK" PRIMARY KEY ("GRN_SUB_CONTRATO", "GRN_NUM_CONTRATO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table GARANTIAH
--------------------------------------------------------

  ALTER TABLE "GARANTIAH" MODIFY ("GRN_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "GARANTIAH" MODIFY ("GRN_SUB_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "GARANTIAH" ADD CONSTRAINT "GARANTIAH_PK" PRIMARY KEY ("GRN_SUB_CONTRATO", "GRN_NUM_CONTRATO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table MOVIMIEN
--------------------------------------------------------

  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_ANO_MOVTO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_MES_MOVTO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_DIA_MOVTO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_SUB_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_FOLIO_OPERA" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_MODULO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_TRANSAC" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_HR_TRANSAC" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_MIN_TRANSAC" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_IMP_MOVTO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_CVE_TIPO_MERCA" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_INSTRUME" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_SEC_EMIS" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_NUM_TITULOS" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_CVE_IMPRE_EDO" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" MODIFY ("MOV_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MOVIMIEN" ADD CONSTRAINT "MOVIMIEN_ANO_OPERA_CK" CHECK (MOV_ANO_MOVTO > 0 AND MOV_MES_MOVTO > 0 AND MOV_DIA_MOVTO > 0) ENABLE;
  ALTER TABLE "MOVIMIEN" ADD CONSTRAINT "MOVIMIEN_PK" PRIMARY KEY ("MOV_ANO_MOVTO", "MOV_MES_MOVTO", "MOV_DIA_MOVTO", "MOV_NUM_CONTRATO", "MOV_SUB_CONTRATO", "MOV_FOLIO_OPERA", "MOV_NUM_MODULO", "MOV_NUM_TRANSAC")
  USING INDEX  ENABLE;
  ALTER TABLE "MOVIMIEN" ADD CONSTRAINT "MOVIMIEN_FOLIO_CK" CHECK (MOV_FOLIO_OPERA > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table MONEDAS
--------------------------------------------------------

  ALTER TABLE "MONEDAS" MODIFY ("MON_NUM_PAIS" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_NOM_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" MODIFY ("MON_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "MONEDAS" ADD CONSTRAINT "MONEDAS_PK" PRIMARY KEY ("MON_NOM_MONEDA", "MON_NUM_PAIS")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAISES
--------------------------------------------------------

  ALTER TABLE "PAISES" MODIFY ("PAI_NUM_PAIS" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PAISES" MODIFY ("PAI_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PAISES" ADD CONSTRAINT "PAISES_PK" PRIMARY KEY ("PAI_NUM_PAIS")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLANES
--------------------------------------------------------

  ALTER TABLE "PLANES" MODIFY ("PLA_CVE_FASE_PROD" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_CVE_CH_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_ANO_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_MES_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_DIA_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_HORA_APLICA" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PLANES" MODIFY ("PLA_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "PLANES" ADD CONSTRAINT "PLANES_PK" PRIMARY KEY ("PLA_CVE_FASE_PROD")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUESTOS
--------------------------------------------------------

  ALTER TABLE "PUESTOS" MODIFY ("PUE_NUM_PUESTO" NOT NULL ENABLE);
  ALTER TABLE "PUESTOS" ADD CONSTRAINT "PUESTOS_PK" PRIMARY KEY ("PUE_NUM_PUESTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORTES
--------------------------------------------------------

  ALTER TABLE "REPORTES" MODIFY ("REP_NUM_REPORTE" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" MODIFY ("REP_CVE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" MODIFY ("REP_CVE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" MODIFY ("REP_CVE_OFICIAL" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" MODIFY ("REP_IMP_COSTO_HOJA" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" MODIFY ("REP_CVE_ST_REPORTE" NOT NULL ENABLE);
  ALTER TABLE "REPORTES" ADD CONSTRAINT "REPORTES_PK" PRIMARY KEY ("REP_NUM_REPORTE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORTE_POLIZA
--------------------------------------------------------

  ALTER TABLE "REPORTE_POLIZA" ADD CONSTRAINT "REPORTE_POLIZA_PK" PRIMARY KEY ("RAS_NUM_CONTRATO", "RAS_FOLIO_OPERA", "RAS_SEC_ASIENTO", "RAS_NUM_CTAM", "RAS_NUM_SCTA", "RAS_NUM_SSCTA", "RAS_NUM_SSSCTA", "RAS_NUM_SSSSCTA", "RAS_NUM_SSSSSCTA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table RUTINAS
--------------------------------------------------------

  ALTER TABLE "RUTINAS" MODIFY ("RUT_ID_RUTINA" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_CVE_IMPRESION" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_CVE_RESP_DATOS" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_NUM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_CVE_BLOQUEO" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" MODIFY ("RUT_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "RUTINAS" ADD CONSTRAINT "RUTINAS_PK" PRIMARY KEY ("RUT_ID_RUTINA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_PUESTO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_NIVEL1" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_NIVEL2" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_NIVEL3" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_NIVEL4" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_NUM_NIVEL5" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_CENTRO_LOGRO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" MODIFY ("USU_CENTRO_COSTO" NOT NULL ENABLE);
  ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("USU_NUM_USUARIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table F_EPASSWORD
--------------------------------------------------------

  ALTER TABLE "F_EPASSWORD" MODIFY ("USU_NUM_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "F_EPASSWORD" MODIFY ("USU_FEC_ERROR" NOT NULL ENABLE);
  ALTER TABLE "F_EPASSWORD" MODIFY ("USU_NUM_ERROR" NOT NULL ENABLE);
  ALTER TABLE "F_EPASSWORD" ADD CONSTRAINT "F_EPASSWORD_PK" PRIMARY KEY ("USU_NUM_USUARIO", "USU_FEC_ERROR")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "FUNCION" ADD CONSTRAINT "FUNCION_PK" PRIMARY KEY ("FUN_ID_OPCION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPOSIT
--------------------------------------------------------

  ALTER TABLE "DEPOSIT" MODIFY ("DPO_FOLIO_RCP" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_FOLIO_OPERA" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_NUM_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_NUM_SEC_OPERA" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_CVE_TIPO_DEP" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_IMP_DEPOSITO" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_NUM_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_ENTIDAD_FIN" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_CONTRATO_INTER" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_POLITICA" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_ANO_RCP" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_MES_RCP" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_DIA_RCP" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" MODIFY ("DPO_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DEPOSIT" ADD CONSTRAINT "DEPOSIT_PK" PRIMARY KEY ("DPO_FOLIO_RCP", "DPO_FOLIO_OPERA", "DPO_CVE_TIPO_DEP")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETLIQUI
--------------------------------------------------------

  ALTER TABLE "DETLIQUI" MODIFY ("DEL_FOLIO_OPERA" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_OPERACION" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_SEC_OPERA" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_MODULO" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_TRANSAC" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_SUB_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_SUB_PROGRAMA" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_PERS_FID" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_TIPO_PERS_FID" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_FOLIO_OPER_SIS" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_IMP_LIQUIDAR" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_CVE_TIPO_LIQ" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_NUM_CHEQUE" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" MODIFY ("DEL_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "DETLIQUI" ADD CONSTRAINT "DETLIQUI_PK" PRIMARY KEY ("DEL_FOLIO_OPERA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table FECCONT
--------------------------------------------------------

  ALTER TABLE "FECCONT" MODIFY ("FCO_CVE_TIPO_FECHA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_DIA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_DIA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_DIA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_APLI_CONTA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_APLI_CONTA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_APLI_CONTA" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_ULT_CIERRE" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_ULT_CIERRE" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_ULT_CIERRE" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIAS_OPER_ANO" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIAS_OPER_SIST" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_INI_OPERS" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_INI_OPERS" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_INI_OPERS" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" MODIFY ("FCO_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "FECCONT" ADD CONSTRAINT "FECCONT_PK" PRIMARY KEY ("FCO_CVE_TIPO_FECHA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table INDICES
--------------------------------------------------------

  ALTER TABLE "INDICES" MODIFY ("IND_CVE_INDICE" CONSTRAINT "SYS_C0046473" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_ANO_INDICE" CONSTRAINT "SYS_C0046474" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_MES_INDICE" CONSTRAINT "SYS_C0046475" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_DIA_INDICE" CONSTRAINT "SYS_C0046476" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_VALOR_INDICE" CONSTRAINT "SYS_C0046477" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_ANO_ALTA_REG" CONSTRAINT "SYS_C0046478" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_MES_ALTA_REG" CONSTRAINT "SYS_C0046479" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_DIA_ALTA_REG" CONSTRAINT "SYS_C0046480" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_ANO_ULT_MOD" CONSTRAINT "SYS_C0046481" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_MES_ULT_MOD" CONSTRAINT "SYS_C0046482" NOT NULL ENABLE);
  ALTER TABLE "INDICES" MODIFY ("IND_DIA_ULT_MOD" CONSTRAINT "SYS_C0046483" NOT NULL ENABLE);
  ALTER TABLE "INDICES" ADD CONSTRAINT "INDICES_PK" PRIMARY KEY ("IND_CVE_INDICE", "IND_ANO_INDICE", "IND_MES_INDICE", "IND_DIA_INDICE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTARIOS
--------------------------------------------------------

  ALTER TABLE "NOTARIOS" MODIFY ("NOT_NUM_NOTARIO" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_NUM_OFIC_NOTA" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_ANO_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_MES_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_DIA_ALTA_REG" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_ANO_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_MES_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" MODIFY ("NOT_DIA_ULT_MOD" NOT NULL ENABLE);
  ALTER TABLE "NOTARIOS" ADD CONSTRAINT "NOTARIOS_PK" PRIMARY KEY ("NOT_NUM_NOTARIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "CONTRATO" MODIFY ("CTO_NUM_CONTRATO" NOT NULL ENABLE);
  ALTER TABLE "CONTRATO" ADD CONSTRAINT "CONTRATO_PK" PRIMARY KEY ("CTO_NUM_CONTRATO")
  USING INDEX  ENABLE;
  ALTER TABLE "CONTRATO" ADD CHECK ( CTO_EST_INTERFID IN ('SI','NO')) ENABLE;
  ALTER TABLE "CONTRATO" ADD CONSTRAINT "CONTRATO_VALIDATI_1718059360" CHECK (CTO_EST_INTERFID IN ('SI', 'NO')) ENABLE;
  ALTER TABLE "CONTRATO" ADD CONSTRAINT "CONTRATO_CK" CHECK ( CTO_NUM_CONTRATO > 0 ) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FIDEICOM
--------------------------------------------------------

  ALTER TABLE "FIDEICOM" ADD CONSTRAINT "CONTRATO_FIDEICOM_FK" FOREIGN KEY ("FID_NUM_CONTRATO")
	  REFERENCES "CONTRATO" ("CTO_NUM_CONTRATO") ENABLE;
  ALTER TABLE "FIDEICOM" ADD CONSTRAINT "ACTIVIDA_FIDEICOM_FK" FOREIGN KEY ("FID_NUM_RAMA", "FID_NUM_SRAMA")
	  REFERENCES "ACTIVIDA" ("ACT_NUM_RAMA", "ACT_NUM_SRAMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table F_USUARIO
--------------------------------------------------------

  ALTER TABLE "F_USUARIO" ADD CONSTRAINT "F_PERFIL_F_USUARIO_FK" FOREIGN KEY ("FPER_ID_PERFIL")
	  REFERENCES "F_PERFIL" ("FPER_ID_PERFIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MONEDAS
--------------------------------------------------------

  ALTER TABLE "MONEDAS" ADD CONSTRAINT "PAISES_MONEDAS_FK" FOREIGN KEY ("MON_NUM_PAIS")
	  REFERENCES "PAISES" ("PAI_NUM_PAIS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORTE_POLIZA
--------------------------------------------------------

  ALTER TABLE "REPORTE_POLIZA" ADD CONSTRAINT "CONTRATO_REPORTE_POLIZA_FK" FOREIGN KEY ("RAS_NUM_CONTRATO")
	  REFERENCES "CONTRATO" ("CTO_NUM_CONTRATO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" ADD CONSTRAINT "ESTRUCTU_USUARIOS_FK" FOREIGN KEY ("USU_NUM_NIVEL1", "USU_NUM_NIVEL2", "USU_NUM_NIVEL3", "USU_NUM_NIVEL4", "USU_NUM_NIVEL5")
	  REFERENCES "ESTRUCTU" ("EST_NUM_NIVEL1", "EST_NUM_NIVEL2", "EST_NUM_NIVEL3", "EST_NUM_NIVEL4", "EST_NUM_NIVEL5") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "CONTRATO" ADD CONSTRAINT "ACTIVIDA_CONTRATO_FK" FOREIGN KEY ("CTO_RAMA", "CTO_SUB_RAMA")
	  REFERENCES "ACTIVIDA" ("ACT_NUM_RAMA", "ACT_NUM_SRAMA") ENABLE;

