

CREATE TABLE "FIDUCIAWEB".f_perfil (
    FPER_ID_PERFIL numeric(10,0) not null,
    FPER_NOMBRE_PERFIL text not null,
    PRIMARY KEY (FPER_ID_PERFIL)
);

GRANT SELECT,UPDATE,DELETE,INSERT ON "FIDUCIAWEB".f_perfil TO "USUARIOCONEXION";

CREATE TABLE "FIDUCIAWEB".f_per_fun (
    FPER_ID_PERFIL numeric(10,0) not null,
    FFUN_ID_FUNCION numeric(10,0) not null,
    PRIMARY KEY (FPER_ID_PERFIL,FFUN_ID_FUNCION)
);

ALTER TABLE f_per_fun
ADD COLUMN ffun_lectura NUMERIC(10,0);

GRANT SELECT,UPDATE,DELETE,INSERT ON "FIDUCIAWEB".f_per_fun TO "USUARIOCONEXION";