INSERT INTO F_PERFIL VALUES (1,'Director Fiduciario');
INSERT INTO F_PERFIL VALUES (2,'Subdirector Servicio al cliente');
INSERT INTO F_PERFIL VALUES (3,'Analista Servicio al cliente');
INSERT INTO F_PERFIL VALUES (4,'Gerente Servicio al cliente');
INSERT INTO F_PERFIL VALUES (5,'Subidrector Control Normativo');
INSERT INTO F_PERFIL VALUES (6,'Gerente  Control Normativo (Contador Fiduciario)');
INSERT INTO F_PERFIL VALUES (7,'Gerente  Control Normativo');
INSERT INTO F_PERFIL VALUES (8,'Subgerente Control Normativo');
INSERT INTO F_PERFIL VALUES (9,'Subdirector Promocion');
INSERT INTO F_PERFIL VALUES (10,'Gerente promotor');
INSERT INTO F_PERFIL VALUES (11,'Promotor');
INSERT INTO F_PERFIL VALUES (12,'Subdirector procesos');

INSERT INTO F_FUNCION VALUES  (1,'ADMINISTRACION.FIDEICOMISOS',null,'ADMINISTRACION.FIDEICOMISOS',1);
INSERT INTO F_FUNCION VALUES  (2,'BIENES.BIENES',null,'BIENES.BIENES',2);
INSERT INTO F_FUNCION VALUES  (3,'BIENES.CARGA_MASIVA',null,'BIENES.CARGA_MASIVA',3);
INSERT INTO F_FUNCION VALUES  (4,'BIENES.INDIVIDUALIZACION',null,'BIENES.INDIVIDUALIZACION',4);
INSERT INTO F_FUNCION VALUES  (5,'BIENES.ADQUIRIENTES',null,'BIENES.ADQUIRIENTES',5);
INSERT INTO F_FUNCION VALUES  (6,'BIENES.LIBERACIONES',null,'BIENES.LIBERACIONES',6);
INSERT INTO F_FUNCION VALUES  (7,'INTERFASES.INTERFASES',null,'INTERFASES.INTERFASES',7);
INSERT INTO F_FUNCION VALUES  (8,'REPORTES.REPORTE_BIENES',null,'REPORTES.REPORTE_BIENES',8);
INSERT INTO F_FUNCION VALUES  (9,'SEGURIDAD.USUARIOS',null,'SEGURIDAD.USUARIOS',9);

INSERT INTO F_PER_FUN VALUES (1,1,1);
INSERT INTO F_PER_FUN VALUES (1,2,1);
INSERT INTO F_PER_FUN VALUES (1,3,1);
INSERT INTO F_PER_FUN VALUES (1,4,1);
INSERT INTO F_PER_FUN VALUES (1,5,1);
INSERT INTO F_PER_FUN VALUES (1,6,1);
INSERT INTO F_PER_FUN VALUES (1,7,1);
INSERT INTO F_PER_FUN VALUES (1,8,1);
INSERT INTO F_PER_FUN VALUES (1,9,1);
INSERT INTO F_PER_FUN VALUES (2,1,0);
INSERT INTO F_PER_FUN VALUES (2,2,0);
INSERT INTO F_PER_FUN VALUES (2,3,0);
INSERT INTO F_PER_FUN VALUES (2,4,0);
INSERT INTO F_PER_FUN VALUES (2,5,0);
INSERT INTO F_PER_FUN VALUES (2,6,0);
INSERT INTO F_PER_FUN VALUES (2,7,0);
INSERT INTO F_PER_FUN VALUES (2,8,0);
INSERT INTO F_PER_FUN VALUES (2,9,0);
INSERT INTO F_PER_FUN VALUES (3,1,0);
INSERT INTO F_PER_FUN VALUES (3,2,0);
INSERT INTO F_PER_FUN VALUES (3,3,0);
INSERT INTO F_PER_FUN VALUES (3,4,0);
INSERT INTO F_PER_FUN VALUES (3,5,0);
INSERT INTO F_PER_FUN VALUES (3,6,0);
INSERT INTO F_PER_FUN VALUES (3,7,0);
INSERT INTO F_PER_FUN VALUES (3,8,0);
INSERT INTO F_PER_FUN VALUES (3,9,0);
INSERT INTO F_PER_FUN VALUES (4,1,0);
INSERT INTO F_PER_FUN VALUES (4,2,0);
INSERT INTO F_PER_FUN VALUES (4,3,0);
INSERT INTO F_PER_FUN VALUES (4,4,0);
INSERT INTO F_PER_FUN VALUES (4,5,0);
INSERT INTO F_PER_FUN VALUES (4,6,0);
INSERT INTO F_PER_FUN VALUES (4,7,0);
INSERT INTO F_PER_FUN VALUES (4,8,0);
INSERT INTO F_PER_FUN VALUES (4,9,0);

INSERT INTO F_PER_FUN VALUES (5,1,1);
INSERT INTO F_PER_FUN VALUES (5,2,1);
INSERT INTO F_PER_FUN VALUES (5,3,1);
INSERT INTO F_PER_FUN VALUES (5,4,1);
INSERT INTO F_PER_FUN VALUES (5,5,1);
INSERT INTO F_PER_FUN VALUES (5,6,1);
INSERT INTO F_PER_FUN VALUES (5,7,1);
INSERT INTO F_PER_FUN VALUES (5,8,1);
INSERT INTO F_PER_FUN VALUES (5,9,1);

INSERT INTO F_PER_FUN VALUES (6,1,1);
INSERT INTO F_PER_FUN VALUES (6,2,1);
INSERT INTO F_PER_FUN VALUES (6,3,1);
INSERT INTO F_PER_FUN VALUES (6,4,1);
INSERT INTO F_PER_FUN VALUES (6,5,1);
INSERT INTO F_PER_FUN VALUES (6,6,1);
INSERT INTO F_PER_FUN VALUES (6,7,1);
INSERT INTO F_PER_FUN VALUES (6,8,1);
INSERT INTO F_PER_FUN VALUES (6,9,1);

INSERT INTO F_PER_FUN VALUES (7,1,1);
INSERT INTO F_PER_FUN VALUES (7,2,1);
INSERT INTO F_PER_FUN VALUES (7,3,1);
INSERT INTO F_PER_FUN VALUES (7,4,1);
INSERT INTO F_PER_FUN VALUES (7,5,1);
INSERT INTO F_PER_FUN VALUES (7,6,1);
INSERT INTO F_PER_FUN VALUES (7,7,1);
INSERT INTO F_PER_FUN VALUES (7,8,1);
INSERT INTO F_PER_FUN VALUES (7,9,1);

INSERT INTO F_PER_FUN VALUES (8,1,1);
INSERT INTO F_PER_FUN VALUES (8,2,1);
INSERT INTO F_PER_FUN VALUES (8,3,1);
INSERT INTO F_PER_FUN VALUES (8,4,1);
INSERT INTO F_PER_FUN VALUES (8,5,1);
INSERT INTO F_PER_FUN VALUES (8,6,1);
INSERT INTO F_PER_FUN VALUES (8,7,1);
INSERT INTO F_PER_FUN VALUES (8,8,1);
INSERT INTO F_PER_FUN VALUES (8,9,1);

INSERT INTO F_PER_FUN VALUES (9,1,1);
INSERT INTO F_PER_FUN VALUES (9,2,1);
INSERT INTO F_PER_FUN VALUES (9,3,1);
INSERT INTO F_PER_FUN VALUES (9,4,1);
INSERT INTO F_PER_FUN VALUES (9,5,1);
INSERT INTO F_PER_FUN VALUES (9,6,1);
INSERT INTO F_PER_FUN VALUES (9,7,1);
INSERT INTO F_PER_FUN VALUES (9,8,1);
INSERT INTO F_PER_FUN VALUES (9,9,1);

INSERT INTO F_PER_FUN VALUES (10,1,1);
INSERT INTO F_PER_FUN VALUES (10,2,1);
INSERT INTO F_PER_FUN VALUES (10,3,1);
INSERT INTO F_PER_FUN VALUES (10,4,1);
INSERT INTO F_PER_FUN VALUES (10,5,1);
INSERT INTO F_PER_FUN VALUES (10,6,1);
INSERT INTO F_PER_FUN VALUES (10,7,1);
INSERT INTO F_PER_FUN VALUES (10,8,1);
INSERT INTO F_PER_FUN VALUES (10,9,1);

INSERT INTO F_PER_FUN VALUES (11,1,1);
INSERT INTO F_PER_FUN VALUES (11,2,1);
INSERT INTO F_PER_FUN VALUES (11,3,1);
INSERT INTO F_PER_FUN VALUES (11,4,1);
INSERT INTO F_PER_FUN VALUES (11,5,1);
INSERT INTO F_PER_FUN VALUES (11,6,1);
INSERT INTO F_PER_FUN VALUES (11,7,1);
INSERT INTO F_PER_FUN VALUES (11,8,1);
INSERT INTO F_PER_FUN VALUES (11,9,1);

INSERT INTO F_PER_FUN VALUES (12,1,1);
INSERT INTO F_PER_FUN VALUES (12,2,1);
INSERT INTO F_PER_FUN VALUES (12,3,1);
INSERT INTO F_PER_FUN VALUES (12,4,1);
INSERT INTO F_PER_FUN VALUES (12,5,1);
INSERT INTO F_PER_FUN VALUES (12,6,1);
INSERT INTO F_PER_FUN VALUES (12,7,1);
INSERT INTO F_PER_FUN VALUES (12,8,1);
INSERT INTO F_PER_FUN VALUES (12,9,1);

DELETE FROM CLAVES WHERE CVE_NUM_CLAVE=30;
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,1,'Director Fiduciario',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,2,'Subdirector Servicio al cliente',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,3,'Analista Servicio al cliente',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,4,'Gerente Servicio al cliente',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,5,'Subidrector Control Normativo',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,6,'Gerente  Control Normativo (Contador Fiduciario)',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,7,'Gerente  Control Normativo',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,8,'Subgerente Control Normativo',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,9,'Subdirector Promocion',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,10,'Gerente promotor',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,11,'Promotor',2020,12,10,2020,12,10,'ACTIVO');
INSERT INTO claves (cve_num_clave, cve_num_sec_clave, cve_desc_clave,  cve_ano_alta_reg, cve_mes_alta_reg, cve_dia_alta_reg, cve_ano_ult_mod, cve_mes_ult_mod, cve_dia_ult_mod, cve_cve_st_clave) VALUES (30,12,'Subdirector procesos',2020,12,10,2020,12,10,'ACTIVO');
COMMIT;
