
package mx.com.inscitech.actinver.ws.watchlist;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "WatchListsService", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                  wsdlLocation =
                  "http://127.0.0.1:7101/FiduciaWeb/WatchListServices/WatchListsServicePort?wsdl#%7Bhttp%3A%2F%2Fwatchlist.ws.actinver.inscitech.com.mx%2F%7DWatchListsService")
public class WatchListsService_Service extends Service {

    private final static URL WATCHLISTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException WATCHLISTSSERVICE_EXCEPTION;
    private final static QName WATCHLISTSSERVICE_QNAME = new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "WatchListsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://127.0.0.1:7101/FiduciaWeb/WatchListServices/WatchListsServicePort?wsdl#%7Bhttp%3A%2F%2Fwatchlist.ws.actinver.inscitech.com.mx%2F%7DWatchListsService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WATCHLISTSSERVICE_WSDL_LOCATION = url;
        WATCHLISTSSERVICE_EXCEPTION = e;
    }

    public WatchListsService_Service() {
        super(__getWsdlLocation(), WATCHLISTSSERVICE_QNAME);
    }

    public WatchListsService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WATCHLISTSSERVICE_QNAME, features);
    }

    public WatchListsService_Service(URL wsdlLocation) {
        super(wsdlLocation, WATCHLISTSSERVICE_QNAME);
    }

    public WatchListsService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WATCHLISTSSERVICE_QNAME, features);
    }

    public WatchListsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WatchListsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WatchListsService
     */
    @WebEndpoint(name = "WatchListsServicePort")
    public WatchListsService getWatchListsServicePort() {
        return super.getPort(new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "WatchListsServicePort"), WatchListsService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WatchListsService
     */
    @WebEndpoint(name = "WatchListsServicePort")
    public WatchListsService getWatchListsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://watchlist.ws.actinver.inscitech.com.mx/", "WatchListsServicePort"), WatchListsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WATCHLISTSSERVICE_EXCEPTION != null) {
            throw WATCHLISTSSERVICE_EXCEPTION;
        }
        return WATCHLISTSSERVICE_WSDL_LOCATION;
    }

}
