package mx.com.inscitech.actinver.ws.watchlist;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class WatchListsServicePortClient {
    public static void main(String[] args) {
        WatchListsService_Service watchListsService_Service = new WatchListsService_Service();
        WatchListsService watchListsService = watchListsService_Service.getWatchListsServicePort();
        // Add your code to call the desired methods.


    }
}
