
package mx.com.inscitech.actinver.ws.watchlist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "WatchListsService", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/")
@XmlSeeAlso({ ObjectFactory.class })
public interface WatchListsService {


    /**
     *
     * @param serviceConfig
     * @return
     *     returns mx.com.inscitech.actinver.ws.watchlist.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setServiceConfig", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.watchlist.SetServiceConfig")
    @ResponseWrapper(localName = "setServiceConfigResponse", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.watchlist.SetServiceConfigResponse")
    @Action(input = "http://watchlist.ws.actinver.inscitech.com.mx/WatchListsService/setServiceConfigRequest",
            output = "http://watchlist.ws.actinver.inscitech.com.mx/WatchListsService/setServiceConfigResponse")
    public ServiceResponse setServiceConfig(@WebParam(name = "serviceConfig", targetNamespace = "") ServiceConfig serviceConfig);

    /**
     *
     * @param entityData
     * @return
     *     returns mx.com.inscitech.actinver.ws.watchlist.ServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchEntity", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                    className = "mx.com.inscitech.actinver.ws.watchlist.SearchEntity")
    @ResponseWrapper(localName = "searchEntityResponse", targetNamespace = "http://watchlist.ws.actinver.inscitech.com.mx/",
                     className = "mx.com.inscitech.actinver.ws.watchlist.SearchEntityResponse")
    @Action(input = "http://watchlist.ws.actinver.inscitech.com.mx/WatchListsService/searchEntityRequest",
            output = "http://watchlist.ws.actinver.inscitech.com.mx/WatchListsService/searchEntityResponse")
    public ServiceResponse searchEntity(@WebParam(name = "entityData", targetNamespace = "") ServiceRequest entityData);

}
